
package CapaInterfaz;

import CapaPersistencia.ArchivadorCiudad;
import CapaLogicaNegocios.Ciudad;
import CapaLogicaNegocios.Cliente;
import CapaLogicaNegocios.Contenedor;
import CapaLogicaNegocios.Descuento;
import CapaLogicaNegocios.Paquete;
import CapaLogicaNegocios.TipoContenido;
import CapaLogicaNegocios.Zona;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class FrmPaquetes extends javax.swing.JFrame {

    private Paquete paquete;
    private Contenedor contenedor = new Contenedor(1000);
    private ArrayList<Ciudad> arrayCiudades = ArchivadorCiudad.getArrayCiudades();
    
    public FrmPaquetes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoContenido = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCboOrigen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCboDestino = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jRdbPerecedero = new javax.swing.JRadioButton();
        jRdbNoPerecedero = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jChkFrecuente = new javax.swing.JCheckBox();
        jChkOro = new javax.swing.JCheckBox();
        jBtnValorarEnvio = new javax.swing.JButton();
        jBtnNuevoPaquete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxaResultado = new javax.swing.JTextArea();
        jTxtPeso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtCostoTraslado = new javax.swing.JTextField();
        jTxtCostoContenido = new javax.swing.JTextField();
        jTxtDescuentos = new javax.swing.JTextField();
        jTxtCostoTotal = new javax.swing.JTextField();
        jBtnSalir = new javax.swing.JButton();
        jBtnAgregarContenedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("Peso");

        jLabel3.setText("Ciudad Origen");

        jLabel4.setText("Ciudad Destino");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Contenido"));

        grupoTipoContenido.add(jRdbPerecedero);
        jRdbPerecedero.setText("Perecedero");

        grupoTipoContenido.add(jRdbNoPerecedero);
        jRdbNoPerecedero.setText("No Perecedero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdbPerecedero)
                    .addComponent(jRdbNoPerecedero))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jRdbPerecedero)
                .addGap(18, 18, 18)
                .addComponent(jRdbNoPerecedero)
                .addContainerGap())
        );

        jLabel6.setText("Descuentos");

        jChkFrecuente.setText("Cliente Frecuente 10%");

        jChkOro.setText("Ciudadano de Oro 5%");

        jBtnValorarEnvio.setText("Valorar Envío");
        jBtnValorarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValorarEnvioActionPerformed(evt);
            }
        });

        jBtnNuevoPaquete.setText("Nuevo Paquete");
        jBtnNuevoPaquete.setEnabled(false);
        jBtnNuevoPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoPaqueteActionPerformed(evt);
            }
        });

        jTxaResultado.setEditable(false);
        jTxaResultado.setColumns(20);
        jTxaResultado.setRows(5);
        jScrollPane2.setViewportView(jTxaResultado);

        jLabel7.setText("Traslado");

        jLabel8.setText("Contenido");

        jLabel9.setText("Descuentos");

        jLabel11.setText("TOTAL");

        jTxtCostoTraslado.setEditable(false);

        jTxtCostoContenido.setEditable(false);
        jTxtCostoContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCostoContenidoActionPerformed(evt);
            }
        });

        jTxtDescuentos.setEditable(false);

        jTxtCostoTotal.setEditable(false);

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jBtnAgregarContenedor.setText("Agregar al Contenedor");
        jBtnAgregarContenedor.setEnabled(false);
        jBtnAgregarContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarContenedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jCboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jCboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jChkFrecuente)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jBtnValorarEnvio)
                                                .addComponent(jChkOro)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtnAgregarContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8))
                                                    .addGap(75, 75, 75))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(67, 67, 67)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTxtDescuentos, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                .addComponent(jTxtCostoContenido, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTxtCostoTraslado, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel11)
                                            .addGap(80, 80, 80)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jBtnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                                .addComponent(jTxtCostoTotal))))
                                    .addComponent(jBtnNuevoPaquete))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)
                        .addGap(16, 16, 16)
                        .addComponent(jChkFrecuente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jChkOro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnValorarEnvio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnAgregarContenedor, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnNuevoPaquete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtCostoTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtCostoContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTxtDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTxtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
     
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jTxtCostoContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCostoContenidoActionPerformed
        
    }//GEN-LAST:event_jTxtCostoContenidoActionPerformed

    private void llenarArrayCiudades(){
//        arrayCiudades.add(new Ciudad("San José", Zona.Area_Metropolitana));
//        arrayCiudades.add(new Ciudad("Alajuela", Zona.Area_Metropolitana));
//        arrayCiudades.add(new Ciudad("Puntarenas", Zona.Pacifico_Central));
//        arrayCiudades.add(new Ciudad("Liberia", Zona.Pacifico_Norte));
//        arrayCiudades.add(new Ciudad("Jacó", Zona.Pacifico_Central));
//        arrayCiudades.add(new Ciudad("Limón", Zona.Zona_Atlantica));
         
      //Llenar el Array de ciudades declarado en los atributos para que a 
     //partir de este se llene el combo en el siguiente método


    }
    private void llenarCombosCiudades() {
        //LLenar combo de ciudades de origen
        
        for (Ciudad ciudad : arrayCiudades) {
            jCboOrigen.addItem(ciudad);
        }
        
        for (Ciudad ciudad : arrayCiudades) {
            jCboDestino.addItem(ciudad);
        }
        
        this.jCboOrigen.setSelectedIndex(-1);
        this.jCboDestino.setSelectedIndex(-1);
    }
    
 private void limpiarCampos() {
        this.jTxtPeso.setText("");
        this.jTxtCostoContenido.setText("");
        this.jTxtCostoTotal.setText("");
        this.jTxtCostoTraslado.setText("");
        this.jTxtDescuentos.setText("");
        this.jTxaResultado.setText("");
        this.jChkFrecuente.setSelected(false);
        this.jChkOro.setSelected(false);
        this.jCboDestino.setSelectedIndex(0);
        this.jCboOrigen.setSelectedIndex(0);
        this.grupoTipoContenido.clearSelection();

    }    
    
    
    
    
    
    private void jBtnValorarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValorarEnvioActionPerformed
       DecimalFormat formatoNumero = new DecimalFormat("#,##0.00");
       

        if (this.jTxtPeso.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe digitar el peso del paquete");
            this.jTxtPeso.requestFocus();
            return;
        }

       
        
        if (this.jCboDestino.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la ciudad destino");
            this.jCboDestino.requestFocus();
            return;
        }

        if (this.jCboOrigen.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la ciudad origen");
            this.jCboOrigen.requestFocus();
            return;
        }

        

       
        double peso = Double.parseDouble(this.jTxtPeso.getText());
      

         //Construcción del paquete
        paquete = new Paquete(peso);
        
        if (this.jChkFrecuente.isSelected()) {
           paquete.agregarDescuento(Descuento.Cliente_Frecuente);
        }

        if (this.jChkOro.isSelected()) {
            paquete.agregarDescuento(Descuento.Ciudadano_Oro);
        }
        
       
        
        paquete.setCiudadOrigen((Ciudad)this.jCboOrigen.getSelectedItem());
        paquete.setCiudadDestino((Ciudad)this.jCboDestino.getSelectedItem());
     
        if(jRdbNoPerecedero.isSelected()){
                 paquete.setTipoContenido(TipoContenido.No_Perecedero);     
        }
        else{
            if(jRdbPerecedero.isSelected()){
                 paquete.setTipoContenido(TipoContenido.Perecedero);     
            }
             else{
                 JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo del contenido");
                 return;
             }     
        }
        
       
        this.jTxtCostoTraslado.setText(formatoNumero.format(paquete.costoTraslado()));
        this.jTxtCostoContenido.setText(formatoNumero.format(paquete.costoTipoContenido()));
        this.jTxtDescuentos.setText(formatoNumero.format(paquete.totalDescuentos()));
        this.jTxtCostoTotal.setText(formatoNumero.format(paquete.costoTotal()));
        this.jTxaResultado.append(paquete.toString());
        this.jBtnAgregarContenedor.setEnabled(true);
        this.jBtnValorarEnvio.setEnabled(false);
    }//GEN-LAST:event_jBtnValorarEnvioActionPerformed

    private void jBtnNuevoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoPaqueteActionPerformed
        limpiarCampos();
        this.jBtnNuevoPaquete.setEnabled(false);
        this.jBtnValorarEnvio.setEnabled(true);
        this.jTxtPeso.requestFocus();
        jCboOrigen.setSelectedIndex(-1);
        jCboDestino.setSelectedIndex(-1);
    }//GEN-LAST:event_jBtnNuevoPaqueteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
        llenarArrayCiudades();
        llenarCombosCiudades();
        this.jBtnNuevoPaquete.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    
    private void jBtnAgregarContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarContenedorActionPerformed
       if(contenedor.cargarPaquete(paquete)==true){
           JOptionPane.showMessageDialog(this, "Paquete cargado correctamente");
       }
       else{
           JOptionPane.showMessageDialog(this, "Paquete no se pudo cargar por exceso de peso");
       }
       jTxaResultado.setText(contenedor.toString());
       jBtnNuevoPaquete.setEnabled(true);
       jBtnAgregarContenedor.setEnabled(false);
    }//GEN-LAST:event_jBtnAgregarContenedorActionPerformed

   
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoTipoContenido;
    private javax.swing.JButton jBtnAgregarContenedor;
    private javax.swing.JButton jBtnNuevoPaquete;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnValorarEnvio;
    private javax.swing.JComboBox<Ciudad> jCboDestino;
    private javax.swing.JComboBox<Ciudad> jCboOrigen;
    private javax.swing.JCheckBox jChkFrecuente;
    private javax.swing.JCheckBox jChkOro;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRdbNoPerecedero;
    private javax.swing.JRadioButton jRdbPerecedero;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTxaResultado;
    private javax.swing.JTextField jTxtCostoContenido;
    private javax.swing.JTextField jTxtCostoTotal;
    private javax.swing.JTextField jTxtCostoTraslado;
    private javax.swing.JTextField jTxtDescuentos;
    private javax.swing.JTextField jTxtPeso;
    // End of variables declaration//GEN-END:variables
}
