/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import CapaEntidad.*;

/**
 *
 * @author johnpaul
 */
public class FrmMostrarContrato extends javax.swing.JFrame {

    /**
     * Creates new form FrmMostrarContrato
     */
    public FrmMostrarContrato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtoMostrarContrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jBtoMostrarContrato.setText("Mostrar contrato");
        jBtoMostrarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoMostrarContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jBtoMostrarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jBtoMostrarContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtoMostrarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoMostrarContratoActionPerformed
        // Pared numero 1
        Tinte tinte1 = new Tinte("T125", 1.15);
        Tinte tinte2 = new Tinte("T135", 2.1);
        Tinte tinte3 = new Tinte("T145", 0.75);
        Pintura pintura1 = new Pintura("P300", "Blanco", 1000, 30);
        pintura1.formulacionPintura(tinte1);
        pintura1.formulacionPintura(tinte2);
        pintura1.formulacionPintura(tinte3);   
        Pared pared1= new Pared(10, 3, pintura1);
        // Pared numero 2
        Tinte tinte4 = new Tinte("T156", 3.25);
        Tinte tinte5 = new Tinte("T110", 1.5);
        Pintura pintura2 = new Pintura("P400", "Rojo", 1500, 40);
        pintura2.formulacionPintura(tinte4);
        pintura2.formulacionPintura(tinte5);
        Pared pared2= new Pared(20, 3, pintura2);
          // Pared numero 3
        Tinte tinte7 = new Tinte("T156", 3.25);
        Tinte tinte8 = new Tinte("T110", 1.5);
        Pintura pintura3 = new Pintura("P400", "Rojo", 1500, 40);
        pintura3.formulacionPintura(tinte7);
        pintura3.formulacionPintura(tinte8); 
        Pared pared3= new Pared(4, 3, pintura3);
        // Pintor de las paredes
        Pintor pintor1 = new Pintor("Pt200", "Juan Perez", 500);
        pintor1.agregarPared(pared1);
        pintor1.agregarPared(pared2);
        pintor1.agregarPared(pared3);
        /// contrato de la por los pintores
        Contrato contrato1= new Contrato();
        contrato1.addPintor(pintor1);
        this.jTextArea1.setText(contrato1.toString());
    }//GEN-LAST:event_jBtoMostrarContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMostrarContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtoMostrarContrato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
