
package CapaInterfaz;




public class FrmMenuPrincipal extends javax.swing.JFrame {

    
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuPrincipal = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuMantenimiento = new javax.swing.JMenu();
        mnuArticulos = new javax.swing.JMenuItem();
        mnuProceso = new javax.swing.JMenu();
        mnuApartado = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        jMnuReporteApartados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Apartados");
        setExtendedState(6);

        mnuArchivo.setText("Archivo");

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        mnuPrincipal.add(mnuArchivo);

        mnuMantenimiento.setText("Mantenimiento");

        mnuArticulos.setText("Articulos");
        mnuArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArticulosActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuArticulos);

        mnuPrincipal.add(mnuMantenimiento);

        mnuProceso.setText("Proceso");

        mnuApartado.setText("Apartado");
        mnuApartado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuApartadoActionPerformed(evt);
            }
        });
        mnuProceso.add(mnuApartado);

        mnuPrincipal.add(mnuProceso);

        mnuReportes.setText("Reportes");

        jMnuReporteApartados.setText("Reporte de Apartados");
        jMnuReporteApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuReporteApartadosActionPerformed(evt);
            }
        });
        mnuReportes.add(jMnuReporteApartados);

        mnuPrincipal.add(mnuReportes);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArticulosActionPerformed
  
        FrmArticulos ventana = new FrmArticulos();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_mnuArticulosActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuApartadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApartadoActionPerformed
    FrmApartados frmApartados = new FrmApartados();
    frmApartados.setVisible(true);
    frmApartados.setLocationRelativeTo(this);

    }//GEN-LAST:event_mnuApartadoActionPerformed

    private void jMnuReporteApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuReporteApartadosActionPerformed
       DlgReporte dlgReporte = new DlgReporte(this,true);
       dlgReporte.setVisible(true);
       dlgReporte.setLocationRelativeTo(this);
       
    }//GEN-LAST:event_jMnuReporteApartadosActionPerformed

  
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuItem jMnuReporteApartados;
    javax.swing.JMenuItem mnuApartado;
    javax.swing.JMenu mnuArchivo;
    javax.swing.JMenuItem mnuArticulos;
    javax.swing.JMenu mnuMantenimiento;
    javax.swing.JMenuBar mnuPrincipal;
    javax.swing.JMenu mnuProceso;
    javax.swing.JMenu mnuReportes;
    javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
