
package capaInterfaz;

import capaLogica.*;




public class FrmFiguras extends javax.swing.JFrame {    
  Figura figura;
   
    public FrmFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnCuadrado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxaCuadrado = new javax.swing.JTextArea();
        jBtnRectangulo = new javax.swing.JButton();
        jBtnTriangulo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxaRectangulo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxaTriangulo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnCuadrado.setText("Cuadrado");
        jBtnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCuadradoActionPerformed(evt);
            }
        });

        jTxaCuadrado.setColumns(20);
        jTxaCuadrado.setRows(5);
        jScrollPane1.setViewportView(jTxaCuadrado);

        jBtnRectangulo.setText("Rectángulo");
        jBtnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRectanguloActionPerformed(evt);
            }
        });

        jBtnTriangulo.setText("Triángulo");
        jBtnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTrianguloActionPerformed(evt);
            }
        });

        jTxaRectangulo.setColumns(20);
        jTxaRectangulo.setRows(5);
        jScrollPane2.setViewportView(jTxaRectangulo);

        jTxaTriangulo.setColumns(20);
        jTxaTriangulo.setRows(5);
        jScrollPane3.setViewportView(jTxaTriangulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jBtnCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jBtnRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jBtnTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRectangulo)
                    .addComponent(jBtnTriangulo))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnCuadrado, jBtnRectangulo, jBtnTriangulo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCuadradoActionPerformed
     this.figura= new Cuadrado("Cuadrado", '<', 6);
     this.jTxaCuadrado.setText(figura.toString());
        
        
    }//GEN-LAST:event_jBtnCuadradoActionPerformed

    private void jBtnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRectanguloActionPerformed
       this.figura= new Rectangulo("Rectangulo", '*',20 , 5);
       this.jTxaRectangulo.setText(figura.toString());
    }//GEN-LAST:event_jBtnRectanguloActionPerformed

    private void jBtnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTrianguloActionPerformed
      this.figura=new Triangulo("Triangulo isoceles angulo recto", '@',10);
      this.jTxaTriangulo.setText(figura.toString());
    
    }//GEN-LAST:event_jBtnTrianguloActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCuadrado;
    private javax.swing.JButton jBtnRectangulo;
    private javax.swing.JButton jBtnTriangulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTxaCuadrado;
    private javax.swing.JTextArea jTxaRectangulo;
    private javax.swing.JTextArea jTxaTriangulo;
    // End of variables declaration//GEN-END:variables
}
