
package capaVista;

import capaLogica.Extra;
import capaLogica.*;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FrmRestaurante extends javax.swing.JFrame {
 Orden orden;
 PlatoItaliano plato;
    DefaultListModel  modeloLista = new DefaultListModel(); 
    DefaultTableModel modeloTabla;   
   
    public FrmRestaurante() {
        initComponents();
         modeloTabla= (DefaultTableModel)this.jTblExtras.getModel();
         this.setTitle("Examen 1 de John Paul Alfaro Carballo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtNumeroOrden = new javax.swing.JTextField();
        jBtnCrearOrden = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRdbPizza = new javax.swing.JRadioButton();
        jRdbPasta = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstTipoPasta = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jCboExtras = new javax.swing.JComboBox<>();
        jBtnAgregarExtra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblExtras = new javax.swing.JTable();
        jChkParaLlevar = new javax.swing.JCheckBox();
        jBtnAgregarPlato = new javax.swing.JButton();
        jBtnNuevoPlato = new javax.swing.JButton();
        jTxtCostoPlato = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxaOrden = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTxtGranTotal = new javax.swing.JTextField();
        jBtnLimpiar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenes"));

        jLabel1.setText("No. de Orden");

        jTxtNumeroOrden.setEditable(false);

        jBtnCrearOrden.setText("Crear Orden");
        jBtnCrearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jTxtNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCrearOrden)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCrearOrden))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de la orden"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Plato"));

        grupoBotones.add(jRdbPizza);
        jRdbPizza.setText("Pizza");
        jRdbPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbPizzaActionPerformed(evt);
            }
        });

        grupoBotones.add(jRdbPasta);
        jRdbPasta.setText("Pasta");
        jRdbPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbPastaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdbPizza)
                    .addComponent(jRdbPasta))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jRdbPizza)
                .addGap(18, 18, 18)
                .addComponent(jRdbPasta)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel2.setText("Tipo de Pasta");

        jLstTipoPasta.setModel(modeloLista);
        jScrollPane1.setViewportView(jLstTipoPasta);

        jLabel3.setText("Extras");

        jBtnAgregarExtra.setText("Agregar Extra");
        jBtnAgregarExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarExtraActionPerformed(evt);
            }
        });

        jTblExtras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTblExtras);

        jChkParaLlevar.setText("Para llevar");

        jBtnAgregarPlato.setText("Agregar Plato a la orden");
        jBtnAgregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarPlatoActionPerformed(evt);
            }
        });

        jBtnNuevoPlato.setText("Nuevo Plato");
        jBtnNuevoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoPlatoActionPerformed(evt);
            }
        });

        jTxtCostoPlato.setEditable(false);

        jLabel4.setText("Costo Plato");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jChkParaLlevar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jCboExtras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jBtnAgregarExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jBtnAgregarPlato)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtnNuevoPlato)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(jTxtCostoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAgregarExtra))
                        .addGap(18, 18, 18)
                        .addComponent(jChkParaLlevar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtCostoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNuevoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAgregarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jTxaOrden.setEditable(false);
        jTxaOrden.setColumns(20);
        jTxaOrden.setRows(5);
        jScrollPane3.setViewportView(jTxaOrden);

        jLabel5.setText("Total Orden");

        jTxtGranTotal.setEditable(false);

        jBtnLimpiar.setText("Limpiar Orden");
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxtGranTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jBtnLimpiar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTxtGranTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jBtnSalir))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.desabilitarBotones();
        this.llenarCombo();
    }//GEN-LAST:event_formWindowOpened
// listo
    private void jBtnAgregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarPlatoActionPerformed
 if(jLstTipoPasta.isSelectionEmpty()){
     JOptionPane.showMessageDialog(this, "Favor seleccionar una pasta");
     return;
 }
 
        if(jRdbPasta.isSelected()){
           plato = new Pasta(jChkParaLlevar.isSelected()); 
           ((Pasta)plato).setTipoPasta((TipoPasta)jLstTipoPasta.getSelectedValue());
        }else{
             plato = new Pizza(jChkParaLlevar.isSelected()); 
             ((Pizza)plato).setTipoPizza((TipoPizza)jLstTipoPasta.getSelectedValue());
        }
        Extra auxExtra=null;
        for (int i = 0; i <modeloTabla.getRowCount(); i++) {
            String extra= (String)modeloTabla.getValueAt(i, 0);
            for (Extra valor : Extra.values()) {
                if(extra.equals(valor.toString())){
                    auxExtra=valor;
                    plato.agregarExtras(auxExtra);
                }
            }
        }
        orden.agregarPlato(plato);
        String costoTotalPlato= Double.toString(plato.precioTotalPlato());
        String totalPagar= Double.toString(orden.calculaTotalOrden());
                  
                this.jTxtCostoPlato.setText(costoTotalPlato);
                this.jTxtGranTotal.setText(totalPagar);
                
                // agregado de forma extra **************************************
                JOptionPane.showMessageDialog(this, plato.toString());
                //********************************************************************
                
                this.jTxaOrden.setText(orden.toString());
        this.jBtnNuevoPlato.setEnabled(true);
        this.jBtnAgregarPlato.setEnabled(false);
        
    }//GEN-LAST:event_jBtnAgregarPlatoActionPerformed
//listo
    private void jBtnAgregarExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarExtraActionPerformed

    Extra extra=(Extra) jCboExtras.getSelectedItem();
    Object [] tabla= new Object[2];
     tabla[0]=extra.toString();
     tabla[1]=extra.getPrecio();
     modeloTabla.addRow(tabla);
    
    
     
    }//GEN-LAST:event_jBtnAgregarExtraActionPerformed
// listo 
    private void jBtnNuevoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoPlatoActionPerformed
       modeloLista.clear();
       this.jCboExtras.setSelectedIndex(0);
       if(modeloTabla.getRowCount()>0){
         int tamanno = modeloTabla.getRowCount()-1;
        for (int i = tamanno; i >= 0; i--) {          
        modeloTabla.removeRow(modeloTabla.getRowCount()-1);
        }
       }
        this.jChkParaLlevar.setSelected(false);
        this.jBtnAgregarPlato.setEnabled(true);
    }//GEN-LAST:event_jBtnNuevoPlatoActionPerformed
// listo 
    private void jBtnCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearOrdenActionPerformed
        // TODO add your handling code here:
        orden = new Orden();
        this.jTxtNumeroOrden.setText(Integer.toString(orden.getNumeroOrden()));
        this.jBtnAgregarPlato.setEnabled(true);
        this.jBtnCrearOrden.setEnabled(false);
    }//GEN-LAST:event_jBtnCrearOrdenActionPerformed
// listo
    private void jRdbPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbPizzaActionPerformed
        // TODO add your handling code here:
        if(jRdbPizza.isSelected()){     
            modeloLista.clear();
            
            this.llenarListaPizza();
        }
    }//GEN-LAST:event_jRdbPizzaActionPerformed
// listo
    private void jRdbPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbPastaActionPerformed
        // TODO add your handling code here:
        // como vacia la lsita ???
        if(jRdbPasta.isSelected()){
            modeloLista.clear();
            this.llenarListaPasta();
        }
    }//GEN-LAST:event_jRdbPastaActionPerformed
// listo
    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        // TODO add your handling code here:
       modeloLista.clear();
       this.jCboExtras.setSelectedIndex(0);
        if(modeloTabla.getRowCount()>0){
             int tamanno = modeloTabla.getRowCount()-1;
        for (int i = tamanno; i >= 0; i--) {          
            modeloTabla.removeRow(modeloTabla.getRowCount()-1);
        }
       }
        this.jChkParaLlevar.setSelected(false);
         orden = new Orden();
        this.jTxtNumeroOrden.setText(Integer.toString(orden.getNumeroOrden()));
        this.jBtnAgregarPlato.setEnabled(true);
        this.jTxtCostoPlato.setText("");
                this.jTxtGranTotal.setText("");
                this.jTxaOrden.setText("");
    }//GEN-LAST:event_jBtnLimpiarActionPerformed
// listo
    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed
 // listo
    
    
   public void vaciarLista(){
      
   } 
   public void llenarListaPizza(){
       for (TipoPizza value : TipoPizza.values()) {
           modeloLista.addElement(value);
       }
   }
   public void llenarListaPasta(){
       for (TipoPasta value : TipoPasta.values()) {
           modeloLista.addElement(value);
       }
   }
   public void desabilitarBotones(){
       this.jBtnAgregarPlato.setEnabled(false);
       this.jBtnNuevoPlato.setEnabled(false);
   }
   public void llenarCombo(){
       for (Extra value : Extra.values()) {
           jCboExtras.addItem(value);
       }
   }
    
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JButton jBtnAgregarExtra;
    private javax.swing.JButton jBtnAgregarPlato;
    private javax.swing.JButton jBtnCrearOrden;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jBtnNuevoPlato;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<Extra> jCboExtras;
    private javax.swing.JCheckBox jChkParaLlevar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<Object> jLstTipoPasta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRdbPasta;
    private javax.swing.JRadioButton jRdbPizza;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblExtras;
    private javax.swing.JTextArea jTxaOrden;
    private javax.swing.JTextField jTxtCostoPlato;
    private javax.swing.JTextField jTxtGranTotal;
    private javax.swing.JTextField jTxtNumeroOrden;
    // End of variables declaration//GEN-END:variables

    
    
}
