/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Vista;
import Capa_Logica_Negocios.*;
import Capa_Acceso_Datos.*;
import java.awt.Color;
import java.awt.Dimension;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Estudiante
 */

   
//  NOTA: Metodo de ***limpiar los campos*** esta comentado(Ln.504 / WindowOpened) para hacer pruebas de una forma mas agil !!

public class FrmVentana_Registro extends javax.swing.JFrame {
   private Usuario usuarioNew=null;
   private Usuario_Tarjeta tarjeta=null;
   
   // estas final me asigan un numero maximo en la cantidad de perfiles 
   // que puede tener cada usuario a la hora de ser registrados
   // TENER CUIDADO CON NUMERO ASIGNADO, ** NO PUEDE SER MAYOR A 5 **
   private final int USUARIO_RESIDENCIAL_PERFIL_CANT=3;
   private final int USUARIO_CORPORATIVO_PERFIL_CANT=5;
      
    /**
     * Creates new form Ventana_RegistroNuevoUsuario
     */
    public FrmVentana_Registro() {
        initComponents();
        this.setTitle("Elaborado por John Paul Alfaro Carballo");
        this.setSize(new Dimension(900,580));
        this.jPnlDatosPersonale.setBackground(new Color(222,222,222,190));
        this.jPnlDatosTecnicos.setBackground(new Color(222,222,222,190));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPnlDatosTecnicos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtNumeroTarjeta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpnAnno = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpnMes = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jTxtPerfil2 = new javax.swing.JTextField();
        jTxtPerfil1 = new javax.swing.JTextField();
        jTxtPerfil4 = new javax.swing.JTextField();
        jTxtPerfil3 = new javax.swing.JTextField();
        jTxtPerfil5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCbxTipoTarjeta = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTxtCVV = new javax.swing.JTextField();
        jBtnRegistrar = new javax.swing.JToggleButton();
        jPnlDatosPersonale = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNombreUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtPaisOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtCorreoElectronico = new javax.swing.JTextField();
        jChkVer = new javax.swing.JCheckBox();
        jTxtConstrasenna = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jRdbUsuarioCorporativo = new javax.swing.JRadioButton();
        jRdbUsuarioResidencial = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jSpnNumeroPerfiles = new javax.swing.JSpinner();
        jBtnAtras = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPnlDatosTecnicos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPnlDatosTecnicos.setOpaque(false);
        jPnlDatosTecnicos.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de tarjeta: ");
        jPnlDatosTecnicos.add(jLabel6);
        jLabel6.setBounds(12, 12, 146, 24);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de tarjeta:");
        jPnlDatosTecnicos.add(jLabel7);
        jLabel7.setBounds(12, 98, 137, 24);

        jTxtNumeroTarjeta.setText("5390395583964086");
        jPnlDatosTecnicos.add(jTxtNumeroTarjeta);
        jTxtNumeroTarjeta.setBounds(12, 48, 340, 32);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de vencimiento:");
        jPnlDatosTecnicos.add(jLabel8);
        jLabel8.setBounds(12, 178, 128, 27);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mes:");
        jPnlDatosTecnicos.add(jLabel9);
        jLabel9.setBounds(30, 210, 37, 22);

        jSpnAnno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSpnAnno.setModel(new javax.swing.SpinnerNumberModel(19, 19, 30, 1));
        jSpnAnno.setOpaque(false);
        jPnlDatosTecnicos.add(jSpnAnno);
        jSpnAnno.setBounds(178, 209, 60, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Año:");
        jPnlDatosTecnicos.add(jLabel10);
        jLabel10.setBounds(140, 210, 32, 24);

        jSpnMes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSpnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jSpnMes.setOpaque(false);
        jPnlDatosTecnicos.add(jSpnMes);
        jSpnMes.setBounds(75, 209, 50, 30);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre de Perfiles:");
        jPnlDatosTecnicos.add(jLabel12);
        jLabel12.setBounds(12, 259, 154, 26);

        jTxtPerfil2.setText("Juanita");
        jPnlDatosTecnicos.add(jTxtPerfil2);
        jTxtPerfil2.setBounds(103, 326, 162, 29);

        jTxtPerfil1.setText("Maria");
        jPnlDatosTecnicos.add(jTxtPerfil1);
        jTxtPerfil1.setBounds(103, 291, 162, 29);

        jTxtPerfil4.setText("Pedro");
        jPnlDatosTecnicos.add(jTxtPerfil4);
        jTxtPerfil4.setBounds(103, 396, 162, 29);

        jTxtPerfil3.setText("Luisa");
        jPnlDatosTecnicos.add(jTxtPerfil3);
        jTxtPerfil3.setBounds(103, 361, 162, 29);

        jTxtPerfil5.setText("Mario");
        jPnlDatosTecnicos.add(jTxtPerfil5);
        jTxtPerfil5.setBounds(103, 431, 162, 33);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pefil 3:");
        jPnlDatosTecnicos.add(jLabel14);
        jLabel14.setBounds(12, 361, 75, 29);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pefil 1:");
        jPnlDatosTecnicos.add(jLabel15);
        jLabel15.setBounds(12, 291, 75, 29);

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Pefil 5:");
        jPnlDatosTecnicos.add(jLabel16);
        jLabel16.setBounds(12, 431, 75, 30);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Pefil 4:");
        jPnlDatosTecnicos.add(jLabel17);
        jLabel17.setBounds(12, 396, 75, 29);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Perfil 2:");
        jPnlDatosTecnicos.add(jLabel18);
        jLabel18.setBounds(12, 326, 60, 29);

        jPnlDatosTecnicos.add(jCbxTipoTarjeta);
        jCbxTipoTarjeta.setBounds(12, 128, 202, 32);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CVV:");
        jPnlDatosTecnicos.add(jLabel19);
        jLabel19.setBounds(232, 103, 62, 16);

        jTxtCVV.setText("123");
        jPnlDatosTecnicos.add(jTxtCVV);
        jTxtCVV.setBounds(232, 128, 120, 32);

        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });
        jPnlDatosTecnicos.add(jBtnRegistrar);
        jBtnRegistrar.setBounds(298, 430, 90, 30);

        getContentPane().add(jPnlDatosTecnicos);
        jPnlDatosTecnicos.setBounds(470, 30, 400, 480);

        jPnlDatosPersonale.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPnlDatosPersonale.setForeground(new java.awt.Color(153, 153, 153));
        jPnlDatosPersonale.setOpaque(false);
        jPnlDatosPersonale.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jPnlDatosPersonale.add(jLabel2);
        jLabel2.setBounds(12, 12, 207, 29);

        jTxtNombreUsuario.setText("Juan Carlos");
        jPnlDatosPersonale.add(jTxtNombreUsuario);
        jTxtNombreUsuario.setBounds(12, 47, 343, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pais de origen: ");
        jPnlDatosPersonale.add(jLabel3);
        jLabel3.setBounds(12, 91, 103, 25);

        jTxtPaisOrigen.setText("Colombia");
        jPnlDatosPersonale.add(jTxtPaisOrigen);
        jTxtPaisOrigen.setBounds(12, 122, 343, 31);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo electronico:");
        jPnlDatosPersonale.add(jLabel4);
        jLabel4.setBounds(12, 171, 142, 25);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña: ");
        jPnlDatosPersonale.add(jLabel5);
        jLabel5.setBounds(12, 246, 100, 27);

        jTxtCorreoElectronico.setText("carlos@hotmail.com");
        jPnlDatosPersonale.add(jTxtCorreoElectronico);
        jTxtCorreoElectronico.setBounds(12, 208, 343, 32);

        jChkVer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jChkVer.setForeground(new java.awt.Color(255, 255, 255));
        jChkVer.setText("Ver");
        jChkVer.setOpaque(false);
        jChkVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkVerActionPerformed(evt);
            }
        });
        jPnlDatosPersonale.add(jChkVer);
        jChkVer.setBounds(321, 279, 50, 32);

        jTxtConstrasenna.setText("holamundo");
        jPnlDatosPersonale.add(jTxtConstrasenna);
        jTxtConstrasenna.setBounds(12, 279, 291, 34);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tipo de usuario:");
        jPnlDatosPersonale.add(jLabel11);
        jLabel11.setBounds(12, 331, 128, 22);

        buttonGroup1.add(jRdbUsuarioCorporativo);
        jRdbUsuarioCorporativo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRdbUsuarioCorporativo.setForeground(new java.awt.Color(255, 255, 255));
        jRdbUsuarioCorporativo.setText("Usuario Corporativo");
        jRdbUsuarioCorporativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbUsuarioCorporativoActionPerformed(evt);
            }
        });
        jPnlDatosPersonale.add(jRdbUsuarioCorporativo);
        jRdbUsuarioCorporativo.setBounds(36, 365, 140, 24);

        buttonGroup1.add(jRdbUsuarioResidencial);
        jRdbUsuarioResidencial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRdbUsuarioResidencial.setForeground(new java.awt.Color(255, 255, 255));
        jRdbUsuarioResidencial.setText("Usuario Residencial");
        jRdbUsuarioResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbUsuarioResidencialActionPerformed(evt);
            }
        });
        jPnlDatosPersonale.add(jRdbUsuarioResidencial);
        jRdbUsuarioResidencial.setBounds(36, 395, 140, 24);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Perfiles disponibles:");
        jPnlDatosPersonale.add(jLabel13);
        jLabel13.setBounds(213, 331, 122, 22);

        jSpnNumeroPerfiles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSpnNumeroPerfiles.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jSpnNumeroPerfiles.setOpaque(false);
        jSpnNumeroPerfiles.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpnNumeroPerfilesStateChanged(evt);
            }
        });
        jPnlDatosPersonale.add(jSpnNumeroPerfiles);
        jSpnNumeroPerfiles.setBounds(223, 365, 50, 30);

        jBtnAtras.setText("Atras");
        jBtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtrasActionPerformed(evt);
            }
        });
        jPnlDatosPersonale.add(jBtnAtras);
        jBtnAtras.setBounds(20, 435, 83, 30);

        getContentPane().add(jPnlDatosPersonale);
        jPnlDatosPersonale.setBounds(20, 30, 400, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Pantalla_Ventanas/fondo_registro_usuario.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -3, 910, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void jBtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FrmVentana_InicioSesion frm = new FrmVentana_InicioSesion();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
    }//GEN-LAST:event_jBtnAtrasActionPerformed

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
    // validaciones de campos vacios y opciones selecionadas para crear el usuario y guardarlo en el archivador
      if(this.validacionCamposNORMALES()==false){
          return;
      }
      
       if(!this.jRdbUsuarioCorporativo.isSelected() && !this.jRdbUsuarioResidencial.isSelected()){
          JOptionPane.showMessageDialog(this,"Favor seleccionar un tipo de cuenta a crear",
                  "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return;
        }
       try {
           // Validacion de la tarjeta por metodos separados   
           if(this.validacionTARJETA()){
               return;
           }
       } catch (ParseException ex) {  }
        
        // captura de datos en variables, ya que fueron validados previamente. y estan CORRECTOS....
        String nombre= this.jTxtNombreUsuario.getText();
                String paisOrigen=this.jTxtPaisOrigen.getText(); 
                        String correo=this.jTxtCorreoElectronico.getText();
                                String contrasenna=this.jTxtConstrasenna.getText();
                                        String numTarjeta=this.jTxtNumeroTarjeta.getText();
                                                String CVV=this.jTxtCVV.getText(); //******ATRIBUTO DE TARJETA*******
                                                        String mes=Integer.toString( (Integer) this.jSpnMes.getValue() );//******ATRIBUTO DE TARJETA*******
                                                                String anno=Integer.toString( (Integer) this.jSpnAnno.getValue() ); //******ATRIBUTO DE TARJETA*******
                                                                       TIPO_TARJETA tipoTarjeta= (TIPO_TARJETA) this.jCbxTipoTarjeta.getSelectedItem();//******ATRIBUTO DE TARJETA********
          
                                                                       // Creacion de la tarjeta para el usuario, ya que fue validada previamente
                                                                       tarjeta= new Usuario_Tarjeta(numTarjeta, CVV, mes, anno, tipoTarjeta);
                                                                       
        // valida si el usuario ya existe dentro de la base de datos
        if(this.jRdbUsuarioCorporativo.isSelected()){   // Si es seleccionado un usuario de TIPO Corporativo
            if(Validacion.validacionUsuarioNuevo(correo)){
            JOptionPane.showMessageDialog(this,"Favor agregar un usuario distinto, el ingresado ya existe como cliente", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return;
            }
          
            // creacion de los usuarios y su respectivo guardado
          this.usuarioNew= new UsuarioCorporativo(nombre, correo, contrasenna, tarjeta);
          ((UsuarioCorporativo)this.usuarioNew).setPaisOrigen(new Usuario_PaisOrigen(paisOrigen));
          usuarioNew.getTarjeta().agregarPago(new Usuario_Pago( LocalDateTime.now(), usuarioNew.costoInscripcion() ) );
          
          if(this.validacionCamposPerfiles()==false){ // valida si se ingreso el nombre de los perfiles
                return;   
                }
          
          this.llenaArrayPerfiles();// Guarda los perfiles dentro del usuario
          Archivador_Usuarios.agregarUsuario(usuarioNew); // Guarda usuario dentro del arhivo, logra la persistencia
         // JOptionPane.showMessageDialog(this,"Usuario creado exitosamente\n"+usuarioNew.toString());
         
         // muestra los datos de la creacion de la cuenta en esta ventana emergente
          FrmVentana_Registro_Informacion ventanaEmergente = new FrmVentana_Registro_Informacion(usuarioNew);
                    ventanaEmergente.setLocationRelativeTo(null);
                    ventanaEmergente.setVisible(true);
            }
        
        
        if(this.jRdbUsuarioResidencial.isSelected()){  // Si es seleccionado un usuario de TIPO Residencial
             if(Validacion.validacionUsuarioNuevo(correo)){
            JOptionPane.showMessageDialog(this,"Favor agregar un usuario distinto, el ingresado ya existe como cliente", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return;
            }
             this.usuarioNew= new UsuarioResidencial(nombre, correo, contrasenna, tarjeta);
              ((UsuarioResidencial)this.usuarioNew).setPaisOrigen(new Usuario_PaisOrigen(paisOrigen));
              usuarioNew.getTarjeta().agregarPago(new Usuario_Pago( LocalDateTime.now(), usuarioNew.costoInscripcion() ) );
              
             if(this.validacionCamposPerfiles()==false){ // valida si se ingreso el nombre de los perfiles
                return;   
                }
             
             this.llenaArrayPerfiles(); // Guarda los perfiles dentro del usuario
             Archivador_Usuarios.agregarUsuario(usuarioNew);// Guarda usuario dentro del arhivo, logra la persistencia
       
             // muestra los datos de la creacion de la cuenta en esta ventana emergente
              FrmVentana_Registro_Informacion ventanaEmergente = new FrmVentana_Registro_Informacion(usuarioNew);
                    ventanaEmergente.setLocationRelativeTo(null);
                     ventanaEmergente.setVisible(true);
        }
        this.limpiarCampos();
        
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // se llenan estrucuturas 
        
   //   this.limpiarCampos();
        this.llenarCombo();
        this.camposDesactivados();
        
    }//GEN-LAST:event_formWindowOpened

    
    // metodos que se encargan de limitar tamanno de los jSpinner y los perfiles que le tocan a cada usuario
    private void jRdbUsuarioCorporativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbUsuarioCorporativoActionPerformed
        // limita el tamanno de los jspinner para asi limitar los perfiles activados
          if(this.jRdbUsuarioCorporativo.isSelected()){
            SpinnerModel modelo = new SpinnerNumberModel(1, 1, USUARIO_CORPORATIVO_PERFIL_CANT, 1);
             this.jSpnNumeroPerfiles.setModel(modelo);
       this.jTxtPerfil1.setEnabled(true);
         this.jTxtPerfil2.setEnabled(false);
          this.jTxtPerfil3.setEnabled(false);
           this.jTxtPerfil4.setEnabled(false);
            this.jTxtPerfil5.setEnabled(false);
        }
    }//GEN-LAST:event_jRdbUsuarioCorporativoActionPerformed

    private void jRdbUsuarioResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbUsuarioResidencialActionPerformed
        // limita el tamanno de los jspinner para asi limitar los perfiles activados
        if(this.jRdbUsuarioResidencial.isSelected()){
             SpinnerModel modelo = new SpinnerNumberModel(1, 1, USUARIO_RESIDENCIAL_PERFIL_CANT, 1);
             this.jSpnNumeroPerfiles.setModel(modelo);
        this.jTxtPerfil1.setEnabled(true);
         this.jTxtPerfil2.setEnabled(false);
          this.jTxtPerfil3.setEnabled(false);
           this.jTxtPerfil4.setEnabled(false);
            this.jTxtPerfil5.setEnabled(false);
        }
    }//GEN-LAST:event_jRdbUsuarioResidencialActionPerformed

    private void jSpnNumeroPerfilesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpnNumeroPerfilesStateChanged
        // dependiendo el valor de este jspinner se activan los perfiles disponibles
        if((Integer)jSpnNumeroPerfiles.getValue()==1){
             this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(false);
              this.jTxtPerfil3.setEnabled(false);
               this.jTxtPerfil4.setEnabled(false);
                this.jTxtPerfil5.setEnabled(false);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==2){
             this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(true);
              this.jTxtPerfil3.setEnabled(false);
               this.jTxtPerfil4.setEnabled(false);
                this.jTxtPerfil5.setEnabled(false);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==3){
             this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(true);
               this.jTxtPerfil3.setEnabled(true);
               this.jTxtPerfil4.setEnabled(false);
                this.jTxtPerfil5.setEnabled(false);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==4){
            this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(true);
               this.jTxtPerfil3.setEnabled(true);
                this.jTxtPerfil4.setEnabled(true);
                this.jTxtPerfil5.setEnabled(false);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==5){
             this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(true);
               this.jTxtPerfil3.setEnabled(true);
                this.jTxtPerfil4.setEnabled(true);
                 this.jTxtPerfil5.setEnabled(true);
              
        }
    }//GEN-LAST:event_jSpnNumeroPerfilesStateChanged

    private void jChkVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkVerActionPerformed
        // Evento que hace posible ver la contrasenna al presion el checkBox  de una fomra agil y estetica
    if (jChkVer.isSelected()) {  //variable boolean
    jTxtConstrasenna.setEchoChar((char)0); // este método es el que hace visible el texto del jPasswordField
    } else {
    jTxtConstrasenna.setEchoChar('*'); // Vuelve a poner asteriscos en la contrasenna
}
    }//GEN-LAST:event_jChkVerActionPerformed
   
    
    //  NOTA: Metodo de ***limpiar los campos*** esta comentado(Ln.483) para hacer pruebas de una forma mas agil !!
    private void camposDesactivados(){
        this.jTxtPerfil1.setEnabled(false);
         this.jTxtPerfil2.setEnabled(false);
          this.jTxtPerfil3.setEnabled(false);
           this.jTxtPerfil4.setEnabled(false);
            this.jTxtPerfil5.setEnabled(false);
    }
    private void limpiarCampos(){
        this.jTxtCVV.setText("");
        this.jTxtConstrasenna.setText("");
        this.jTxtCorreoElectronico.setText("");
        this.jTxtNombreUsuario.setText("");
        this.jTxtNumeroTarjeta.setText("");
        this.jTxtPaisOrigen.setText("");
        this.jTxtPerfil1.setText("");
        this.jTxtPerfil2.setText("");
        this.jTxtPerfil3.setText("");
        this.jTxtPerfil4.setText("");
        this.jTxtPerfil5.setText("");
        this.jSpnAnno.setValue(19);
        this.jSpnMes.setValue(1);
        this.jSpnNumeroPerfiles.setValue(1);
    }
    private void llenarCombo(){
          for (TIPO_TARJETA value : TIPO_TARJETA.values()) {
              this.jCbxTipoTarjeta.addItem(value);
          }
    }
    private boolean validacionCamposNORMALES() {
            if(this.jTxtNombreUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar un usuario", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(this.jTxtCorreoElectronico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar un correo electronico", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(this.jTxtConstrasenna.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar una contraseña", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(this.jTxtPaisOrigen.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar un pais de origen", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(this.jTxtCVV.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar codigo CVV de la tarjeta", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
           return false;
        }
        if(this.jTxtNumeroTarjeta.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar una tarjeta valida", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(this.jCbxTipoTarjeta.getSelectedIndex()==-1){
             JOptionPane.showMessageDialog(this,"Favor agregar un tipo de tarjeta", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
//        if(!this.jRdbUsuarioCorporativo.isSelected() && !this.jRdbUsuarioResidencial.isSelected()){
//              JOptionPane.showMessageDialog(this,"Favor seleccionar un tipo de cuenta a crear", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
//            return;
//        }
        // validacion de existencia de ste usuarios
//        String correo=this.jTxtCorreoElectronico.getText();
//        if(Validacion.validacionUsuarioNuevo(correo)){
//            JOptionPane.showMessageDialog(this,"Favor agregar un usuario distinto, el ingresado ya existe");
//            return;
//       }

        return true;
    }
    private boolean validacionTARJETA() throws ParseException{
        String numTarjeta=this.jTxtNumeroTarjeta.getText();
        String CVV=this.jTxtCVV.getText();
        String mes=Integer.toString( (Integer) this.jSpnMes.getValue() );
        String anno=Integer.toString( (Integer) this.jSpnAnno.getValue() );
        TIPO_TARJETA tipoTarjeta= (TIPO_TARJETA) this.jCbxTipoTarjeta.getSelectedItem();
        
        if(!Validacion.validarFechaTarjeta(mes,anno)){
             JOptionPane.showMessageDialog(this,"Favor agregar una fecha valida de tarjeta",
                     "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return true;  
        }
           if(!Validacion.validarNumeroTarjeta(numTarjeta)){
             JOptionPane.showMessageDialog(this,"Favor agregar un numero de tarjeta valido", 
                     "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return true;  
        }
              if(!Validacion.validarTipoTarjeta(numTarjeta, CVV, tipoTarjeta)){
             JOptionPane.showMessageDialog(this,"Favor agregar un tipo valido de tarjeta",
                     "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return true;  
        }
           return false;
    }
    private void llenaArrayPerfiles(){
          if((Integer)jSpnNumeroPerfiles.getValue()==1){
             usuarioNew.agregarPerfil(this.jTxtPerfil1.getText());
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==2){
             usuarioNew.agregarPerfil(this.jTxtPerfil1.getText());
              usuarioNew.agregarPerfil(this.jTxtPerfil2.getText());
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==3){
             usuarioNew.agregarPerfil(this.jTxtPerfil1.getText());
             usuarioNew.agregarPerfil(this.jTxtPerfil2.getText());
             usuarioNew.agregarPerfil(this.jTxtPerfil3.getText() );
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==4){
             usuarioNew.agregarPerfil(this.jTxtPerfil1.getText());
             usuarioNew.agregarPerfil(this.jTxtPerfil2.getText());
             usuarioNew.agregarPerfil(this.jTxtPerfil3.getText() );
             usuarioNew.agregarPerfil( this.jTxtPerfil4.getText() );
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==5){
             usuarioNew.agregarPerfil(this.jTxtPerfil1.getText());
             usuarioNew.agregarPerfil(this.jTxtPerfil2.getText());
             usuarioNew.agregarPerfil(this.jTxtPerfil3.getText() );
             usuarioNew.agregarPerfil( this.jTxtPerfil4.getText() );
             usuarioNew.agregarPerfil(this.jTxtPerfil5.getText());  
        }
    }
    private boolean validacionCamposPerfiles(){
          if((Integer)jSpnNumeroPerfiles.getValue()==1){ //******************1
                if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==2){//******************2
              if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
         if(this.jTxtPerfil2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 2", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==3){//******************3
         if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
         if(this.jTxtPerfil2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 2", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
          if(this.jTxtPerfil3.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 3", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==4){//******************4
              if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;        }
         if(this.jTxtPerfil2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 2", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;       
         }
          if(this.jTxtPerfil3.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 3", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;       
          }
           if(this.jTxtPerfil4.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 4", "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
           
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==5){//******************5
              if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
         if(this.jTxtPerfil2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 2" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return false;
        }
          if(this.jTxtPerfil3.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 3" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
           return false;
        }
           if(this.jTxtPerfil4.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 4" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
           return false;
        }
            if(this.jTxtPerfil5.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 5" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
           return false;
        } 
        }
      return true;
    }
    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmVentana_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmVentana_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmVentana_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmVentana_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmVentana_Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton jBtnAtras;
    private javax.swing.JToggleButton jBtnRegistrar;
    private javax.swing.JComboBox<TIPO_TARJETA> jCbxTipoTarjeta;
    private javax.swing.JCheckBox jChkVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPnlDatosPersonale;
    private javax.swing.JPanel jPnlDatosTecnicos;
    private javax.swing.JRadioButton jRdbUsuarioCorporativo;
    private javax.swing.JRadioButton jRdbUsuarioResidencial;
    private javax.swing.JSpinner jSpnAnno;
    private javax.swing.JSpinner jSpnMes;
    private javax.swing.JSpinner jSpnNumeroPerfiles;
    private javax.swing.JTextField jTxtCVV;
    private javax.swing.JPasswordField jTxtConstrasenna;
    private javax.swing.JTextField jTxtCorreoElectronico;
    private javax.swing.JTextField jTxtNombreUsuario;
    private javax.swing.JTextField jTxtNumeroTarjeta;
    private javax.swing.JTextField jTxtPaisOrigen;
    private javax.swing.JTextField jTxtPerfil1;
    private javax.swing.JTextField jTxtPerfil2;
    private javax.swing.JTextField jTxtPerfil3;
    private javax.swing.JTextField jTxtPerfil4;
    private javax.swing.JTextField jTxtPerfil5;
    // End of variables declaration//GEN-END:variables
}
