/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Vista;

import java.awt.Color; 
import java.awt.Dimension;
import  Capa_Logica_Negocios.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author johnpaul
 */
public class JDlgVentana_AdminCatalogo extends javax.swing.JDialog {
    
    // Hacen funcionar el archivo correctamente
    ContenidoAudioVisual contenidoAudioVisual=null;
    private String codigo;
    private TIPO_ADMIN_OPCION tipoAdministrador;
    
    
    // arraylist auxiliares
    private ArrayList <TIPOS_IDIOMAS> arrayIdiomas;
    private ArrayList <Temporada> arrayTemporada;
    DefaultListModel modeloOrigen  = new DefaultListModel();
      
      // contador de numero de temporada por el cual va   **NO SE USA
      private int contadorTemporada=1;
    
    
    public JDlgVentana_AdminCatalogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Elaborado por John Paul Alfaro Carballo");
        this.setSize(new Dimension(700,525));
         this.jPnlDatosGenerales.setBackground(new Color(222,222,222,190));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.arrayIdiomas= new ArrayList();
        this.arrayTemporada= new ArrayList();
                
    }
    public JDlgVentana_AdminCatalogo(String codigop, TIPO_ADMIN_OPCION tipo){
        this.codigo=codigop;
        this.tipoAdministrador=tipo;
        
           try {
        initComponents();
        this.setSize(new Dimension(700,525));
        this.jPnlDatosGenerales.setBackground(new Color(222,222,222,190));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.arrayIdiomas= new ArrayList();
        this.arrayTemporada= new ArrayList();
        
        } catch (Exception e) {  }
           
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGroupTipoContenido = new javax.swing.ButtonGroup();
        jPnlDatosGenerales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigoContenidoAudiovisual = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtTituloContenidoAudioVisual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtFechaCreacionContenidoAudiovisual = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jCbxGeneros = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jRbdPelicula = new javax.swing.JRadioButton();
        jRbdSerie = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPnlPelicula = new javax.swing.JPanel();
        jPnlPeliculaSub = new javax.swing.JPanel();
        jChxGanadoOscar = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jTxtNombreDirector = new javax.swing.JTextField();
        jPnlSerie = new javax.swing.JPanel();
        jPnlSerieSub = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSpnNumeroCapitulos = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jSpnNumeroTemporada = new javax.swing.JSpinner();
        jBtnIngresarTemporada = new javax.swing.JButton();
        jBtnIngresarTemporadaExtra = new javax.swing.JButton();
        jChxEsCompleta = new javax.swing.JCheckBox();
        jChxEsOriginal = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstIdiomasDisponibles = new javax.swing.JList<>();
        jBtnAgregarIdioma = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jBtnIngresarContenido = new javax.swing.JButton();
        jBtnAtras = new javax.swing.JButton();
        jLblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Codigo:");

        try {
            jTxtCodigoContenidoAudiovisual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtCodigoContenidoAudiovisual.setText("TWD-001");
        jTxtCodigoContenidoAudiovisual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigoContenidoAudiovisualFocusLost(evt);
            }
        });

        jLabel2.setText("Titulo del contenido:");

        jTxtTituloContenidoAudioVisual.setText("The Walking Dead");

        jLabel3.setText("Año y mes de creacion del contenido:");

        jLabel4.setText("Formato: Mes/Año");

        try {
            jTxtFechaCreacionContenidoAudiovisual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Genero:");

        jLabel7.setText("Tipo de contenido audiovisual:");

        jBtnGroupTipoContenido.add(jRbdPelicula);
        jRbdPelicula.setText("Pelicula");
        jRbdPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbdPeliculaActionPerformed(evt);
            }
        });

        jBtnGroupTipoContenido.add(jRbdSerie);
        jRbdSerie.setText("Serie");
        jRbdSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbdSerieActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jChxGanadoOscar.setText("Ha ganado un Oscar?");

        jLabel8.setText("Nombre del director:");

        jTxtNombreDirector.setText("Tarantinno");

        javax.swing.GroupLayout jPnlPeliculaSubLayout = new javax.swing.GroupLayout(jPnlPeliculaSub);
        jPnlPeliculaSub.setLayout(jPnlPeliculaSubLayout);
        jPnlPeliculaSubLayout.setHorizontalGroup(
            jPnlPeliculaSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPeliculaSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlPeliculaSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNombreDirector)
                    .addGroup(jPnlPeliculaSubLayout.createSequentialGroup()
                        .addGroup(jPnlPeliculaSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChxGanadoOscar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPnlPeliculaSubLayout.setVerticalGroup(
            jPnlPeliculaSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPeliculaSubLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jChxGanadoOscar)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNombreDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlPeliculaLayout = new javax.swing.GroupLayout(jPnlPelicula);
        jPnlPelicula.setLayout(jPnlPeliculaLayout);
        jPnlPeliculaLayout.setHorizontalGroup(
            jPnlPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPeliculaSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnlPeliculaLayout.setVerticalGroup(
            jPnlPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlPeliculaSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pelicula", jPnlPelicula);

        jLabel9.setText("Area de ingreso de temporadas:");

        jLabel10.setText("Numero de temporada: ");

        jSpnNumeroCapitulos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel11.setText("Cantidad de capitulos: ");

        jSpnNumeroTemporada.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jBtnIngresarTemporada.setText("Ingresar");
        jBtnIngresarTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarTemporadaActionPerformed(evt);
            }
        });

        jBtnIngresarTemporadaExtra.setText("Extra");
        jBtnIngresarTemporadaExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarTemporadaExtraActionPerformed(evt);
            }
        });

        jChxEsCompleta.setText("Esta completa ?");

        javax.swing.GroupLayout jPnlSerieSubLayout = new javax.swing.GroupLayout(jPnlSerieSub);
        jPnlSerieSub.setLayout(jPnlSerieSubLayout);
        jPnlSerieSubLayout.setHorizontalGroup(
            jPnlSerieSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSerieSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlSerieSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPnlSerieSubLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jBtnIngresarTemporadaExtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnIngresarTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlSerieSubLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpnNumeroCapitulos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlSerieSubLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPnlSerieSubLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpnNumeroTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jChxEsCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPnlSerieSubLayout.setVerticalGroup(
            jPnlSerieSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSerieSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jChxEsCompleta)
                .addGap(9, 9, 9)
                .addGroup(jPnlSerieSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpnNumeroTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlSerieSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpnNumeroCapitulos, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPnlSerieSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIngresarTemporadaExtra)
                    .addComponent(jBtnIngresarTemporada))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPnlSerieLayout = new javax.swing.GroupLayout(jPnlSerie);
        jPnlSerie.setLayout(jPnlSerieLayout);
        jPnlSerieLayout.setHorizontalGroup(
            jPnlSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlSerieSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnlSerieLayout.setVerticalGroup(
            jPnlSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlSerieSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Serie", jPnlSerie);

        jChxEsOriginal.setText("Contenido orginal de la plataforma?");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Idiomas disponibles:"));
        jPanel2.setOpaque(false);

        jLstIdiomasDisponibles.setModel(modeloOrigen);
        jScrollPane1.setViewportView(jLstIdiomasDisponibles);

        jBtnAgregarIdioma.setText("Agregar");
        jBtnAgregarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarIdiomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgregarIdioma))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jBtnAgregarIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlDatosGeneralesLayout = new javax.swing.GroupLayout(jPnlDatosGenerales);
        jPnlDatosGenerales.setLayout(jPnlDatosGeneralesLayout);
        jPnlDatosGeneralesLayout.setHorizontalGroup(
            jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtTituloContenidoAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                            .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtCodigoContenidoAudiovisual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCbxGeneros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFechaCreacionContenidoAudiovisual, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 79, Short.MAX_VALUE)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                        .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(jRbdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRbdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jChxEsOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnlDatosGeneralesLayout.setVerticalGroup(
            jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigoContenidoAudiovisual, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbxGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRbdPelicula)
                    .addComponent(jRbdSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChxEsOriginal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(jTxtTituloContenidoAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFechaCreacionContenidoAudiovisual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        getContentPane().add(jPnlDatosGenerales);
        jPnlDatosGenerales.setBounds(20, 20, 660, 390);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones finales"));
        jPanel1.setOpaque(false);

        jBtnIngresarContenido.setText("Terminado");
        jBtnIngresarContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarContenidoActionPerformed(evt);
            }
        });

        jBtnAtras.setText("Atras");
        jBtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBtnIngresarContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jBtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIngresarContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 410, 300, 90);

        jLblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Pantalla_Ventanas/FondoPantallaAdminReporte1.jpg"))); // NOI18N
        getContentPane().add(jLblFondo);
        jLblFondo.setBounds(0, 0, 705, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
  //===================================================================================================
    // metodos que se ejecutan dal abrirse esta ventana
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // acciones que se jecutan al abrir
              switch (tipoAdministrador) {
            case AGREGAR:
               this.camposAgregar();
                setTitle("Nuevo Contenido Audiovisual");
                break;
            case MODIFICAR:
                this.camposDesactivadosModificar();
                setTitle("Modificar Contenido Audiovisual");
                break;
            case CONSULTAR:
                this.camposDescativadosConsultar();
                setTitle("Consulta de un Contenido Audiovisual");
                break;
        }
         jTxtCodigoContenidoAudiovisual.setText(codigo);
         this.limpiarCamposTODOS();
         try {
           contenidoAudioVisual = ContenidoAudioVisual.consultarContenidoAudiovisual(codigo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar el contenido audiovisual\n"+
                e.toString() + "\n" + e.getMessage());
        }  
        if(contenidoAudioVisual != null){
           this.llenoCamposModificar();
            
        }
        
    }//GEN-LAST:event_formWindowOpened
//====================================================================================================
 
  
    
//************************************************************************************************************************************************************
  // Eventos de botones principales de la ventana
    
    // ******boton que se encarga de crear el contenido audiovisual  MAS IMPORTANTE
    private void jBtnIngresarContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarContenidoActionPerformed
   //     this.validacionCamposVacios();
        
        String titulo= this.jTxtTituloContenidoAudioVisual.getText();
                String codigop=this.jTxtCodigoContenidoAudiovisual.getText();
                        String [] annoCreacion=this.jTxtFechaCreacionContenidoAudiovisual.getText().split("/");
                                TIPO_GENERO genero=(TIPO_GENERO)this.jCbxGeneros.getSelectedItem();
                                Boolean esOriginal= this.jChxEsOriginal.isSelected();
                                      
//                                int mes=Integer.parseInt(this.conersionNumero(annoCreacion[0]));
//                                int anno=Integer.parseInt(annoCreacion[1]);
//                                this.validacionFecha(mes, anno);
                                
                                if(this.jRbdPelicula.isSelected()){ // si el administrador selecciona crear una pelicula
                                    this.validacionCamposPelicula();
                                    String director= this.jTxtNombreDirector.getText();
                                    Boolean ganOscar=this.jChxGanadoOscar.isSelected();
  ContenidoAudioVisual contenido = new ContenidoPelicula(ganOscar,director,esOriginal,codigop,titulo,LocalDateTime.of(1980,4, 1, 1, 1));
                                    contenido.setGenero(genero);                            
                                    for (TIPOS_IDIOMAS arrayIdioma : arrayIdiomas) {
                                        contenido.agregarIdioma(arrayIdioma);
                                    }
                                    FrmVentana_Admin.setContenidoAudVis(contenido);
                                    System.out.println(contenido.toString()+">>>>VENTANA DIALOGO>>>>");
                                    this.dispose();
                                }
   //------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                if(this.jRbdSerie.isSelected()){// si el administrador selecciona crear una serie
                                    Boolean esCompleta= this.jChxEsCompleta.isSelected();
  ContenidoAudioVisual contenido = new ContenidoSerie(codigo, titulo,LocalDateTime.of(89,4, 1, 1, 1),esOriginal,esCompleta);
                                    contenido.setGenero(genero);
                                    for (TIPOS_IDIOMAS arrayIdioma : arrayIdiomas) {
                                        contenido.agregarIdioma(arrayIdioma);
                                     }
                                     for (Temporada temporada : arrayTemporada) {
                                        ((ContenidoSerie)contenido).agregarTemporada(temporada);
                                    }
                                     //Lo mando a la otra ventana principal para que pueda ser agregado al archivo
                                     FrmVentana_Admin.setContenidoAudVis(contenido);
                                      System.out.println(contenido.toString()+">>>>0>>>>");
                                     this.dispose();
                                }                 
    }//GEN-LAST:event_jBtnIngresarContenidoActionPerformed

    private void jBtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtrasActionPerformed
        FrmVentana_Admin.setContenidoAudVis(null);
        this.dispose();
    }//GEN-LAST:event_jBtnAtrasActionPerformed
//************************************************************************************************************************************************************
  
    
    
  //-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    // Eventos de la ventana interna de << SERIE >>
    private void jBtnIngresarTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarTemporadaActionPerformed
        // guarda cada temporada en el arraylist
        int temporada= (Integer)this.jSpnNumeroTemporada.getValue();
        int episodios= (Integer)this.jSpnNumeroCapitulos.getValue();
        Temporada temp = new Temporada(temporada, episodios);
        
        if(this.arrayTemporada.size()>=1){
                if(!Validacion.validacionExistenciaTemporada(temporada, arrayTemporada)){
                    this.arrayTemporada.add(temp);
                }else{
                JOptionPane.showMessageDialog(this, "Favor ingresar otra temporada, la ingresada ya existe para la serie");
                return;
                }
        } 
        this.arrayTemporada.add(temp);
        
        
        this.jBtnIngresarTemporada.setEnabled(false);
        this.jBtnIngresarTemporadaExtra.setEnabled(true);
        contadorTemporada++;

    }//GEN-LAST:event_jBtnIngresarTemporadaActionPerformed

    private void jBtnIngresarTemporadaExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarTemporadaExtraActionPerformed
        // setea los contadores nuevamente a su incial valor:
        this.jBtnIngresarTemporadaExtra.setEnabled(false);
        this.jBtnIngresarTemporada.setEnabled(true);
        SpinnerModel modelo1 = new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1);
          SpinnerModel modelo2 = new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1);
             this.jSpnNumeroCapitulos.setModel(modelo1);
             this.jSpnNumeroTemporada.setModel(modelo2);
        
    }//GEN-LAST:event_jBtnIngresarTemporadaExtraActionPerformed
 //-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  
    
    // <<<<<<<<<<<<<<<<<<<<<<<<<<<ACCIONES EXTRA>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    // Boton para agregar los Idiomas y temporadas  al  ArraylistAuxiliar, para luego cargarlo en el de la serie
    private void jBtnAgregarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarIdiomaActionPerformed
        // pasa de la lista al arrayList
       int indice = jLstIdiomasDisponibles.getSelectedIndex();
       if(indice >= 0){
           this.arrayIdiomas.add(this.jLstIdiomasDisponibles.getSelectedValue());
           modeloOrigen.remove(indice);
       }
       else{
           JOptionPane.showMessageDialog(null, "Debe seleccionar un idioma de la lista");
       }
    }//GEN-LAST:event_jBtnAgregarIdiomaActionPerformed

    private void jRbdPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbdPeliculaActionPerformed
        // Accion que sucede cuando este boton es seleccionado
        if(this.jRbdPelicula.isSelected()){
            this.jTabbedPane1.setEnabledAt(1, false);
            this.jTabbedPane1.setEnabledAt(0, true);
            this.jTabbedPane1.setSelectedIndex(0);
            this.camposActivadosPelicula();
            this.camposDesactivadosSerie();
        }
    }//GEN-LAST:event_jRbdPeliculaActionPerformed

    private void jRbdSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbdSerieActionPerformed
        // accion que sucede cuando este boton es seleccionado
        if(this.jRbdSerie.isSelected()){
            this.jTabbedPane1.setEnabledAt(0, false);
            this.jTabbedPane1.setEnabledAt(1, true);
            this.jTabbedPane1.setSelectedIndex(1);
            this.camposActivadosSerie();
            this.camposDesactivadosPelicula();
        }
    }//GEN-LAST:event_jRbdSerieActionPerformed

    private void jTxtCodigoContenidoAudiovisualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigoContenidoAudiovisualFocusLost
   if(tipoAdministrador== tipoAdministrador.AGREGAR){
            try {
                codigo= jTxtCodigoContenidoAudiovisual.getText();
                contenidoAudioVisual = ContenidoAudioVisual.consultarContenidoAudiovisual(codigo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Error al buscar el contenido audio visual\n"+e.toString() + "\n" +e.getMessage());
            }
            if(contenidoAudioVisual != null){
                JOptionPane.showMessageDialog(this,
                    "El contenido audiovisual existe");
                jTxtCodigoContenidoAudiovisual.selectAll();
                return;
            }
        }
    }//GEN-LAST:event_jTxtCodigoContenidoAudiovisualFocusLost

    // <<<<<<<<<<<<<<<<<<<<<<<<<<<ACCIONES EXTRA>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    
    
    
    
    // <<<<<<<METODOS INTERNOS (VALIDACIONES / (ACTIVO/INACTIVO) >>>>>>>
    
    public void limpiarCamposTODOS(){
        this.jTxtNombreDirector.setText("");
       // this.jTxtCodigoContenidoAudiovisual.setText("");
        this.jTxtFechaCreacionContenidoAudiovisual.setText("");
        this.jTxtTituloContenidoAudioVisual.setText("");
        
    } 
    public void validacionCamposVacios(){
        if(this.jTxtCodigoContenidoAudiovisual.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor ingresar un codigo del contenido valido");
            return;
        }
        if(this.jTxtFechaCreacionContenidoAudiovisual.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor ingresar un fecha de creacion del contenido valido");
            return;
        }
        if(this.jTxtTituloContenidoAudioVisual.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor ingresar un titulo del contenido valido");
            return;
        }
        if(this.jCbxGeneros.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "Favor seleccionar un genero valido");
            return;
        }
//        if(this.jLstIdiomasDisponibles.getSelectedIndex()==-1){
//            JOptionPane.showMessageDialog(this, "Favor seleccionar un idioma disponible valido");
//            return;
//        }
                
        
    }// valida TODOS los campos vacios
    public void validacionCamposPelicula(){
        if(this.jTxtNombreDirector.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor ingresar un nombre de director valido");
            return;       
        }
    } // valida el campo de pelicula
    public boolean validacionCampoPeliculaOscar(){
        if(this.jChxGanadoOscar.isSelected()){
            return true;
        }
        return false;
    }
    public boolean validacionCampoEsOriginal(){
        if(this.jChxEsOriginal.isSelected()){
            return true;
        }
        return false;
    }
    public String conersionNumero(String numero){
        String mesAux=numero;
         if(numero.contains("0")){
             mesAux= numero.replace("0", "");
          }
         return mesAux;
    }
    public void validacionFecha(int mes, int anno){
        if(mes>12 ||mes <=0){
             JOptionPane.showMessageDialog(this, "Favor ingresar un mes valido");
            return;  
        }
        if(anno>20){
             JOptionPane.showMessageDialog(this, "Favor ingresar un año valido");
            return;  
        }
    }
    public void camposDesactivadosPelicula(){
        this.jTxtNombreDirector.setEnabled(false);
        this.jChxGanadoOscar.setEnabled(false);
    }
    public void camposActivadosPelicula(){
        this.jTxtNombreDirector.setEnabled(true);
        this.jChxGanadoOscar.setEnabled(true);
    }
    public void camposDesactivadosSerie(){
        this.jSpnNumeroCapitulos.setEnabled(false);
        this.jSpnNumeroTemporada.setEnabled(false);
        this.jBtnIngresarTemporada.setEnabled(false);
        this.jBtnIngresarTemporadaExtra.setEnabled(false);
    }
    public void camposActivadosSerie(){
        this.jSpnNumeroCapitulos.setEnabled(true);
        this.jSpnNumeroTemporada.setEnabled(true);
        this.jBtnIngresarTemporada.setEnabled(true);
        this.jBtnIngresarTemporadaExtra.setEnabled(true);
    }
    
    public void camposDescativadosConsultar(){
        this.jTxtCodigoContenidoAudiovisual.setEditable(false);
        this.jTxtTituloContenidoAudioVisual.setEditable(false);
        this.jTxtFechaCreacionContenidoAudiovisual.setEditable(false);
        this.jTxtNombreDirector.setEditable(false);
        this.jBtnAgregarIdioma.setEnabled(false);
        
    }
    public void camposDesactivadosModificar(){
        this.jTxtCodigoContenidoAudiovisual.setEditable(false);
         this.jTxtTituloContenidoAudioVisual.selectAll();
        this.jTxtFechaCreacionContenidoAudiovisual.selectAll();
        this.jTxtNombreDirector.selectAll();
    }
    public void camposAgregar(){
        this.jBtnIngresarTemporadaExtra.setEnabled(false);
        this.llenoComboGeneros();
        this.llenoListaIdiomas();
        this.limpiarCamposTODOS();
    }
   
    //Lleno estructuras dentro del JDlg (Combos y listas)
    public void llenoListaIdiomas(){
          //Declara un modelo para cada Lista (Hay que digitarlo)
        for (TIPOS_IDIOMAS value : TIPOS_IDIOMAS.values()) {
            modeloOrigen.addElement(value);
        }
    }
    public void llenoComboGeneros(){
        for (TIPO_GENERO genero : TIPO_GENERO.values()) {
            this.jCbxGeneros.addItem(genero);
        }
    }
    public void llenoCamposModificar(){
        this.jTxtCodigoContenidoAudiovisual.setText(contenidoAudioVisual.getCodigo());
        this.jTxtFechaCreacionContenidoAudiovisual.setText(contenidoAudioVisual.devuelveAnnoCreacionAux());
        this.jTxtTituloContenidoAudioVisual.setText(contenidoAudioVisual.getTitulo());
        for (TIPOS_IDIOMAS value : contenidoAudioVisual.getIdiomasDisponibles()) {
            modeloOrigen.addElement(value);
        }
        this.jCbxGeneros.addItem(contenidoAudioVisual.getGenero());
        for (TIPO_GENERO genero : TIPO_GENERO.values()) {
            if(!contenidoAudioVisual.getGenero().equals(genero)){
            this.jCbxGeneros.addItem(genero);
            }
        }
        this.jBtnAgregarIdioma.setEnabled(false);
        this.jChxEsOriginal.setSelected(contenidoAudioVisual.isEsOriginal());
        if(contenidoAudioVisual instanceof ContenidoPelicula){
            this.jRbdPelicula.setSelected(true);
            this.jTxtNombreDirector.setText(((ContenidoPelicula)contenidoAudioVisual).getDirector());
        }
        if(contenidoAudioVisual instanceof ContenidoSerie){
            this.jRbdSerie.setSelected(true);
            
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVentana_AdminCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVentana_AdminCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVentana_AdminCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVentana_AdminCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVentana_AdminCatalogo dialog = new JDlgVentana_AdminCatalogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregarIdioma;
    private javax.swing.JButton jBtnAtras;
    private javax.swing.ButtonGroup jBtnGroupTipoContenido;
    private javax.swing.JButton jBtnIngresarContenido;
    private javax.swing.JButton jBtnIngresarTemporada;
    private javax.swing.JButton jBtnIngresarTemporadaExtra;
    private javax.swing.JComboBox<TIPO_GENERO> jCbxGeneros;
    private javax.swing.JCheckBox jChxEsCompleta;
    private javax.swing.JCheckBox jChxEsOriginal;
    private javax.swing.JCheckBox jChxGanadoOscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblFondo;
    private javax.swing.JList<TIPOS_IDIOMAS> jLstIdiomasDisponibles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlDatosGenerales;
    private javax.swing.JPanel jPnlPelicula;
    private javax.swing.JPanel jPnlPeliculaSub;
    private javax.swing.JPanel jPnlSerie;
    private javax.swing.JPanel jPnlSerieSub;
    private javax.swing.JRadioButton jRbdPelicula;
    private javax.swing.JRadioButton jRbdSerie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpnNumeroCapitulos;
    private javax.swing.JSpinner jSpnNumeroTemporada;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField jTxtCodigoContenidoAudiovisual;
    private javax.swing.JFormattedTextField jTxtFechaCreacionContenidoAudiovisual;
    private javax.swing.JTextField jTxtNombreDirector;
    private javax.swing.JTextField jTxtTituloContenidoAudioVisual;
    // End of variables declaration//GEN-END:variables
}
