
package capaInterfaz;

import capaEntidad.Sucursal;


public class FrmMenuPrincipal extends javax.swing.JFrame {    
   
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuMantenimiento = new javax.swing.JMenu();
        mnuProducto = new javax.swing.JMenuItem();
        mnuProceso = new javax.swing.JMenu();
        mnuFacturar = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenu();
        mnuConsultaSucursales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mnuArchivo.setText("Archivo");

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        mnuMantenimiento.setText("Mantenimiento");

        mnuProducto.setText("Producto");
        mnuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductoActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuProducto);

        jMenuBar1.add(mnuMantenimiento);

        mnuProceso.setText("Proceso");

        mnuFacturar.setText("Facturar");
        mnuFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacturarActionPerformed(evt);
            }
        });
        mnuProceso.add(mnuFacturar);

        jMenuBar1.add(mnuProceso);

        mnuReporte.setText("Reportes");

        mnuConsultaSucursales.setText("Consulta por Sucursales");
        mnuConsultaSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaSucursalesActionPerformed(evt);
            }
        });
        mnuReporte.add(mnuConsultaSucursales);

        jMenuBar1.add(mnuReporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductoActionPerformed

        FrmProducto oVentana = new FrmProducto();
        oVentana.setVisible(true);
        oVentana.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuProductoActionPerformed

    private void mnuFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacturarActionPerformed
   
        FrmFactura oVentana = new FrmFactura();
        oVentana.setVisible(true);
        oVentana.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuFacturarActionPerformed

    private void mnuConsultaSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaSucursalesActionPerformed
       
        dglConsulta oVentana = new dglConsulta(this,true);
        oVentana.setLocationRelativeTo(this);
        oVentana.setVisible(true);
    }//GEN-LAST:event_mnuConsultaSucursalesActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
      
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JMenu mnuArchivo;
    javax.swing.JMenuItem mnuConsultaSucursales;
    javax.swing.JMenuItem mnuFacturar;
    javax.swing.JMenu mnuMantenimiento;
    javax.swing.JMenu mnuProceso;
    javax.swing.JMenuItem mnuProducto;
    javax.swing.JMenu mnuReporte;
    javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
