/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Vista;
import Capa_Logica_Negocios.*;
import Capa_Acceso_Datos.*;
import java.awt.Color;
import java.awt.Dimension;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Estudiante
 */
public class Ventana_RegistroNuevoUsuario extends javax.swing.JFrame {
   private Usuario usuarioNew=null;
   private TIPO_TARJETA tipoTarjeta=null;
    
    
    /**
     * Creates new form Ventana_RegistroNuevoUsuario
     */
    public Ventana_RegistroNuevoUsuario() {
        initComponents();
        this.setTitle("Elaborado por John Paul Alfaro Carballo");
        this.setSize(new Dimension(900,580));
        this.jPnlDatosPersonales.setBackground(new Color(222,222,222,190));
        this.jPnlDatosTecnicos.setBackground(new Color(222,222,222,190));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPnlDatosTecnicos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtNumeroTarjeta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpnAnno = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpnMes = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jTxtPerfil2 = new javax.swing.JTextField();
        jTxtPerfil1 = new javax.swing.JTextField();
        jTxtPerfil4 = new javax.swing.JTextField();
        jTxtPerfil3 = new javax.swing.JTextField();
        jTxtPerfil5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jBtnRegistrar = new javax.swing.JToggleButton();
        jCbxTipoTarjeta = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTxtCVV = new javax.swing.JTextField();
        jPnlDatosPersonales = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNombreUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtPaisOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtCorreoElectronico = new javax.swing.JTextField();
        jChkVer = new javax.swing.JCheckBox();
        jTxtConstrasenna = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jRdbUsuarioCorporativo = new javax.swing.JRadioButton();
        jRdbUsuarioResidencial = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jSpnNumeroPerfiles = new javax.swing.JSpinner();
        jBtnAtras = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel6.setText("Numero de tarjeta: ");

        jLabel7.setText("Tipo de tarjeta:");

        jTxtNumeroTarjeta.setText("5390395583964086");

        jLabel8.setText("Fecha de vencimiento:");

        jLabel9.setText("Mes:");

        jSpnAnno.setModel(new javax.swing.SpinnerNumberModel(19, 19, 30, 1));

        jLabel10.setText("Año:");

        jSpnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jLabel12.setText("Nombre de Perfiles:");

        jLabel14.setText("Pefil 3:");

        jLabel15.setText("Pefil 1:");

        jLabel16.setText("Pefil 5:");

        jLabel17.setText("Pefil 4:");

        jLabel18.setText("Perfil 2:");

        jBtnRegistrar.setBackground(new java.awt.Color(102, 153, 0));
        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        jLabel19.setText("CVV:");

        jTxtCVV.setText("123");

        javax.swing.GroupLayout jPnlDatosTecnicosLayout = new javax.swing.GroupLayout(jPnlDatosTecnicos);
        jPnlDatosTecnicos.setLayout(jPnlDatosTecnicosLayout);
        jPnlDatosTecnicosLayout.setHorizontalGroup(
            jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosTecnicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDatosTecnicosLayout.createSequentialGroup()
                        .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(16, 16, 16)
                        .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPnlDatosTecnicosLayout.createSequentialGroup()
                                .addComponent(jTxtPerfil5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnRegistrar)
                                .addContainerGap())
                            .addGroup(jPnlDatosTecnicosLayout.createSequentialGroup()
                                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtPerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtPerfil2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtPerfil4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(135, 135, 135))))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDatosTecnicosLayout.createSequentialGroup()
                        .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlDatosTecnicosLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlDatosTecnicosLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpnMes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSpnAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtNumeroTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlDatosTecnicosLayout.createSequentialGroup()
                            .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCbxTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtCVV))))))
        );
        jPnlDatosTecnicosLayout.setVerticalGroup(
            jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosTecnicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtCVV)
                    .addComponent(jCbxTipoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpnAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpnMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtPerfil2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtPerfil4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPnlDatosTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtPerfil5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPnlDatosTecnicos);
        jPnlDatosTecnicos.setBounds(470, 30, 400, 480);

        jPnlDatosPersonales.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Nombre");

        jLabel3.setText("Pais de origen: ");

        jLabel4.setText("Correo electronico:");

        jLabel5.setText("Contraseña: ");

        jTxtCorreoElectronico.setText("maria22@hotmail.com");

        jChkVer.setText("Ver");
        jChkVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkVerActionPerformed(evt);
            }
        });

        jTxtConstrasenna.setText("holamundo");

        jLabel11.setText("Tipo de usuario:");

        buttonGroup1.add(jRdbUsuarioCorporativo);
        jRdbUsuarioCorporativo.setText("Usuario Corporativo");
        jRdbUsuarioCorporativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbUsuarioCorporativoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRdbUsuarioResidencial);
        jRdbUsuarioResidencial.setText("Usuario Residencial");
        jRdbUsuarioResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbUsuarioResidencialActionPerformed(evt);
            }
        });

        jLabel13.setText("Perfiles disponibles:");

        jSpnNumeroPerfiles.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jSpnNumeroPerfiles.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpnNumeroPerfilesStateChanged(evt);
            }
        });

        jBtnAtras.setBackground(new java.awt.Color(204, 204, 0));
        jBtnAtras.setText("Atras");
        jBtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlDatosPersonalesLayout = new javax.swing.GroupLayout(jPnlDatosPersonales);
        jPnlDatosPersonales.setLayout(jPnlDatosPersonalesLayout);
        jPnlDatosPersonalesLayout.setHorizontalGroup(
            jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtPaisOrigen)
                        .addComponent(jTxtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPnlDatosPersonalesLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRdbUsuarioCorporativo)
                                    .addComponent(jRdbUsuarioResidencial))))
                        .addGap(56, 56, 56)
                        .addGroup(jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpnNumeroPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jTxtConstrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jChkVer)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlDatosPersonalesLayout.setVerticalGroup(
            jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkVer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtConstrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpnNumeroPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRdbUsuarioCorporativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRdbUsuarioResidencial)
                .addGap(18, 18, 18)
                .addComponent(jBtnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPnlDatosPersonales);
        jPnlDatosPersonales.setBounds(20, 30, 400, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Pantalla_Ventanas/fondo_registro_usuario.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -3, 910, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    
    private void jBtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnAtrasActionPerformed

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        // validaciones de campos vacios y opciones selecionadas para crear el usuario y guardarlo en el archivador
        this.validacionCamposNORMALES();
        // captura de datos en variables, ya que fueron validados previamente. y estan CORRECTOS....
        String nombre= this.jTxtNombreUsuario.getText();
                String paisOrigen=this.jTxtPaisOrigen.getText(); 
                        String correo=this.jTxtCorreoElectronico.getText();
                                String contrasenna=this.jTxtConstrasenna.getText();
                                        String numTarjeta=this.jTxtNumeroTarjeta.getText();
                                                String CVV=this.jTxtCVV.getText(); 
                                                        String mes=Integer.toString( (Integer) this.jSpnMes.getValue() );
                                                                String anno=Integer.toString( (Integer) this.jSpnAnno.getValue() ); 
                                                                        tipoTarjeta= (TIPO_TARJETA) this.jCbxTipoTarjeta.getSelectedItem();
        // creacion de los OBJETOS usuario nuevos y agregacion a la persistencia
        if(this.jRdbUsuarioCorporativo.isSelected()){
            if(Validacion.validacionUsuarioNuevo(correo)){
            JOptionPane.showMessageDialog(this,"Favor agregar un usuario distinto, el ingresado ya existe como cliente");
            return;
            }
          this.usuarioNew= new UsuarioCorporativo(nombre, correo, contrasenna, numTarjeta, tipoTarjeta);
           ((UsuarioCorporativo)this.usuarioNew).setAnnoVencimiento(anno);
           ((UsuarioCorporativo)this.usuarioNew).setMesVencimineto(mes);
           ((UsuarioCorporativo)this.usuarioNew).setCVV(CVV);
           ((UsuarioCorporativo)this.usuarioNew).setPaisOrigen(paisOrigen);
          this.validacionCamposPerfiles();
          this.llenaArrayPerfiles();
          Archivador_Usuarios.agregarUsuario(usuarioNew);
          JOptionPane.showMessageDialog(this,"Usuario creado exitosamente\n"+usuarioNew.toString());
        }
        if(this.jRdbUsuarioResidencial.isSelected()){
             if(Validacion.validacionUsuarioNuevo(correo)){
            JOptionPane.showMessageDialog(this,"Favor agregar un usuario distinto, el ingresado ya existe como cliente");
            return;
            }
             this.usuarioNew= new UsuarioResidencial(nombre, correo, contrasenna, numTarjeta, tipoTarjeta);
              ((UsuarioResidencial)this.usuarioNew).setAnnoVencimiento(anno);
              ((UsuarioResidencial)this.usuarioNew).setMesVencimineto(mes);
              ((UsuarioResidencial)this.usuarioNew).setCVV(CVV);
              ((UsuarioResidencial)this.usuarioNew).setPaisOrigen(paisOrigen);
             this.validacionCamposPerfiles();
             this.llenaArrayPerfiles();
             Archivador_Usuarios.agregarUsuario(usuarioNew);
             JOptionPane.showMessageDialog(this,"Usuario creado exitosamente\n"+usuarioNew.toString());
        }
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // se llenan estrucuturas 
   //     this.limpiarCampos();
        this.llenarCombo();
        this.camposDesactivados();
    }//GEN-LAST:event_formWindowOpened

    
    // metodos que se encargan d elimitar tamanno de los jSpinner y los perfiles que le tocan a cada usuario
    private void jRdbUsuarioCorporativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbUsuarioCorporativoActionPerformed
        // limita el tamanno de los jspinner para asi limitar los perfiles activados
          if(this.jRdbUsuarioCorporativo.isSelected()){
            SpinnerModel modelo = new SpinnerNumberModel(1, 1, 5, 1);
             this.jSpnNumeroPerfiles.setModel(modelo);
       this.jTxtPerfil1.setEnabled(true);
         this.jTxtPerfil2.setEnabled(false);
          this.jTxtPerfil3.setEnabled(false);
           this.jTxtPerfil4.setEnabled(false);
            this.jTxtPerfil5.setEnabled(false);
        }
    }//GEN-LAST:event_jRdbUsuarioCorporativoActionPerformed

    private void jRdbUsuarioResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbUsuarioResidencialActionPerformed
        // limita el tamanno de los jspinner para asi limitar los perfiles activados
        if(this.jRdbUsuarioResidencial.isSelected()){
             SpinnerModel modelo = new SpinnerNumberModel(1, 1, 3, 1);
             this.jSpnNumeroPerfiles.setModel(modelo);
        this.jTxtPerfil1.setEnabled(true);
         this.jTxtPerfil2.setEnabled(false);
          this.jTxtPerfil3.setEnabled(false);
           this.jTxtPerfil4.setEnabled(false);
            this.jTxtPerfil5.setEnabled(false);
        }
    }//GEN-LAST:event_jRdbUsuarioResidencialActionPerformed

    private void jSpnNumeroPerfilesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpnNumeroPerfilesStateChanged
        // dependiendo el valor de este jspinner se activan los perfiles disponibles
        if((Integer)jSpnNumeroPerfiles.getValue()==1){
             this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(false);
              this.jTxtPerfil3.setEnabled(false);
               this.jTxtPerfil4.setEnabled(false);
                this.jTxtPerfil5.setEnabled(false);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==2){
             this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(true);
              this.jTxtPerfil3.setEnabled(false);
               this.jTxtPerfil4.setEnabled(false);
                this.jTxtPerfil5.setEnabled(false);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==3){
             this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(true);
               this.jTxtPerfil3.setEnabled(true);
               this.jTxtPerfil4.setEnabled(false);
                this.jTxtPerfil5.setEnabled(false);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==4){
            this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(true);
               this.jTxtPerfil3.setEnabled(true);
                this.jTxtPerfil4.setEnabled(true);
                this.jTxtPerfil5.setEnabled(false);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==5){
             this.jTxtPerfil1.setEnabled(true);
              this.jTxtPerfil2.setEnabled(true);
               this.jTxtPerfil3.setEnabled(true);
                this.jTxtPerfil4.setEnabled(true);
                 this.jTxtPerfil5.setEnabled(true);
              
        }
    }//GEN-LAST:event_jSpnNumeroPerfilesStateChanged

    private void jChkVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkVerActionPerformed
        // Evento que hace posible ver la contrasenna al presion el checkBox  de una fomra agil y estetica
    if (jChkVer.isSelected()) {  //variable boolean
    jTxtConstrasenna.setEchoChar((char)0); // este método es el que hace visible el texto del jPasswordField
    } else {
    jTxtConstrasenna.setEchoChar('*'); // Vuelve a poner asteriscos en la contrasenna
}
    }//GEN-LAST:event_jChkVerActionPerformed
  
    
    //  NOTA: Metodo de limpiar los campos esta comentado para hacer pruebas de una forma mas agil!!
    private void camposDesactivados(){
        this.jTxtPerfil1.setEnabled(false);
         this.jTxtPerfil2.setEnabled(false);
          this.jTxtPerfil3.setEnabled(false);
           this.jTxtPerfil4.setEnabled(false);
            this.jTxtPerfil5.setEnabled(false);
    }
    private void limpiarCampos(){
        this.jTxtCVV.setText("");
        this.jTxtConstrasenna.setText("");
        this.jTxtCorreoElectronico.setText("");
        this.jTxtNombreUsuario.setText("");
        this.jTxtNumeroTarjeta.setText("");
        this.jTxtPaisOrigen.setText("");
        this.jTxtPerfil1.setText("");
        this.jTxtPerfil2.setText("");
        this.jTxtPerfil3.setText("");
        this.jTxtPerfil4.setText("");
        this.jTxtPerfil5.setText("");
        this.jSpnAnno.setValue(19);
        this.jSpnMes.setValue(1);
        this.jSpnNumeroPerfiles.setValue(1);
    }
    private void llenarCombo(){
          for (TIPO_TARJETA value : TIPO_TARJETA.values()) {
              this.jCbxTipoTarjeta.addItem(value);
          }
    }
    private void validacionCamposNORMALES(){
            if(this.jTxtNombreUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar un usuario");
            return;
        }
        if(this.jTxtCorreoElectronico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar un correo electronico");
            return;
        }
        if(this.jTxtConstrasenna.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar una contraseña");
            return;
        }
        if(this.jTxtPaisOrigen.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar un pais de origen");
            return;
        }
        if(this.jTxtCVV.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar codigo CVV de la tarjeta");
            return;
        }
        if(this.jTxtNumeroTarjeta.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor agregar una tarjeta valida");
            return;
        }
        if(this.jCbxTipoTarjeta.getSelectedIndex()==-1){
             JOptionPane.showMessageDialog(this,"Favor agregar un tipo de tarjeta");
            return;
        }
        
        // validacion de existencia de ste usuarios
//        String correo=this.jTxtCorreoElectronico.getText();
//        if(Validacion.validacionUsuarioNuevo(correo)){
//            JOptionPane.showMessageDialog(this,"Favor agregar un usuario distinto, el ingresado ya existe");
//            return;
//       }

        // validacion de la tarjeta ingresada
        String numTarjeta=this.jTxtNumeroTarjeta.getText();
        String CVV=this.jTxtCVV.getText();
        String mes=Integer.toString( (Integer) this.jSpnMes.getValue() );
        String anno=Integer.toString( (Integer) this.jSpnAnno.getValue() );
        tipoTarjeta= (TIPO_TARJETA) this.jCbxTipoTarjeta.getSelectedItem();
        try {  if(!Validacion.validacionTarjeta(numTarjeta, CVV, mes, anno, tipoTarjeta)){
                JOptionPane.showMessageDialog(this,"Favor revisar la tarjeta ingresada");
                 return;
             }
          } catch (ParseException ex) {  }
    }
    private void llenaArrayPerfiles(){
        Usuario_Perfil perfil1,perfil2,perfil3,perfil4,perfil5;
          if((Integer)jSpnNumeroPerfiles.getValue()==1){
              perfil1= new Usuario_Perfil( this.jTxtPerfil1.getText() );
             usuarioNew.agregarPerfil(perfil1);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==2){
            perfil1= new Usuario_Perfil( this.jTxtPerfil1.getText() );
            perfil2= new Usuario_Perfil( this.jTxtPerfil2.getText() );
             usuarioNew.agregarPerfil(perfil1);
              usuarioNew.agregarPerfil(perfil2);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==3){
            perfil1= new Usuario_Perfil( this.jTxtPerfil1.getText() );
            perfil2= new Usuario_Perfil( this.jTxtPerfil2.getText() );
            perfil3= new Usuario_Perfil( this.jTxtPerfil3.getText() );
             usuarioNew.agregarPerfil(perfil1);
             usuarioNew.agregarPerfil(perfil2);
             usuarioNew.agregarPerfil(perfil3);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==4){
            perfil1= new Usuario_Perfil( this.jTxtPerfil1.getText() );
            perfil2= new Usuario_Perfil( this.jTxtPerfil2.getText() );
            perfil3= new Usuario_Perfil( this.jTxtPerfil3.getText() );
            perfil4= new Usuario_Perfil( this.jTxtPerfil4.getText() );
             usuarioNew.agregarPerfil(perfil1);
             usuarioNew.agregarPerfil(perfil2);
             usuarioNew.agregarPerfil(perfil3);
             usuarioNew.agregarPerfil(perfil4);
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==5){
            perfil1= new Usuario_Perfil( this.jTxtPerfil1.getText() );
            perfil2= new Usuario_Perfil( this.jTxtPerfil2.getText() );
            perfil3= new Usuario_Perfil( this.jTxtPerfil3.getText() );
            perfil4= new Usuario_Perfil( this.jTxtPerfil4.getText() );
            perfil5= new Usuario_Perfil( this.jTxtPerfil5.getText() );
             usuarioNew.agregarPerfil(perfil1);
             usuarioNew.agregarPerfil(perfil2);
             usuarioNew.agregarPerfil(perfil3);
             usuarioNew.agregarPerfil(perfil4);
             usuarioNew.agregarPerfil(perfil5);  
        }
    }
    private void validacionCamposPerfiles(){
          if((Integer)jSpnNumeroPerfiles.getValue()==1){ //******************1
                if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1");
            return;
        }
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==2){//******************2
              if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1");
            return;
        }
         if(this.jTxtPerfil2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 2");
            return;
        }
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==3){//******************3
         if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1");
            return;
        }
         if(this.jTxtPerfil2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 2");
            return;
        }
          if(this.jTxtPerfil3.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 3");
            return;
        }
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==4){//******************4
              if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1");
            return;
        }
         if(this.jTxtPerfil2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 2");
            return;
        }
          if(this.jTxtPerfil3.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 3");
            return;
        }
           if(this.jTxtPerfil4.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 4");
            return;
        }
           
        }
        if((Integer)jSpnNumeroPerfiles.getValue()==5){//******************5
              if(this.jTxtPerfil1.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 1");
            return;
        }
         if(this.jTxtPerfil2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 2");
            return;
        }
          if(this.jTxtPerfil3.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 3");
            return;
        }
           if(this.jTxtPerfil4.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 4");
            return;
        }
            if(this.jTxtPerfil5.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor llenar el Perfil 5");
            return;
        } 
        }
      
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_RegistroNuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton jBtnAtras;
    private javax.swing.JToggleButton jBtnRegistrar;
    private javax.swing.JComboBox<TIPO_TARJETA> jCbxTipoTarjeta;
    private javax.swing.JCheckBox jChkVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPnlDatosPersonales;
    private javax.swing.JPanel jPnlDatosTecnicos;
    private javax.swing.JRadioButton jRdbUsuarioCorporativo;
    private javax.swing.JRadioButton jRdbUsuarioResidencial;
    private javax.swing.JSpinner jSpnAnno;
    private javax.swing.JSpinner jSpnMes;
    private javax.swing.JSpinner jSpnNumeroPerfiles;
    private javax.swing.JTextField jTxtCVV;
    private javax.swing.JPasswordField jTxtConstrasenna;
    private javax.swing.JTextField jTxtCorreoElectronico;
    private javax.swing.JTextField jTxtNombreUsuario;
    private javax.swing.JTextField jTxtNumeroTarjeta;
    private javax.swing.JTextField jTxtPaisOrigen;
    private javax.swing.JTextField jTxtPerfil1;
    private javax.swing.JTextField jTxtPerfil2;
    private javax.swing.JTextField jTxtPerfil3;
    private javax.swing.JTextField jTxtPerfil4;
    private javax.swing.JTextField jTxtPerfil5;
    // End of variables declaration//GEN-END:variables
}
