
package CapaInterfaz;

import CapaLogicaNegocios.*;
import capaPersistencia.ArchivadorArticulo;
import java.util.ArrayList;
import javafx.scene.shape.Arc;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmArticulos extends javax.swing.JFrame {
 DefaultTableModel modeloTabla;
  Articulo articulo;

   
    public FrmArticulos() {
        initComponents();
        this.modeloTabla= (DefaultTableModel)this.jTblArticulos.getModel();
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnGuardar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblArticulos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salvar_Disco2.png"))); // NOI18N
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setFocusable(false);
        jBtnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnGuardar);

        jBtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificar.png"))); // NOI18N
        jBtnModificar.setText("Modificar");
        jBtnModificar.setFocusable(false);
        jBtnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnModificar);

        jBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.jpg"))); // NOI18N
        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.setFocusable(false);
        jBtnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnEliminar);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setFocusable(false);
        jBtnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnCancelar);
        jToolBar1.add(jSeparator1);

        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.setFocusable(false);
        jBtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnSalir);

        jLabel1.setText("Código");

        jLabel2.setText("Descripción");

        jLabel3.setText("Precio");

        jTblArticulos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblArticulos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTblArticulosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTblArticulosFocusLost(evt);
            }
        });
        jTblArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblArticulos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        String codigo,descripcion;
        double precio;
        codigo = jTxtCodigo.getText();
        descripcion = jTxtDescripcion.getText();
        precio = Double.parseDouble(jTxtPrecio.getText());
       //Almacena el nuevo artículo en el Archivador de artículos
        if(codigo.equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar un codigo");
            return;
        }
         if(descripcion.equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar una descripcion correcta");
            return;
        }
          if(precio<0){
            JOptionPane.showMessageDialog(this, "Ingresar un codigo");
            return;
        }
          articulo= new Articulo(codigo, descripcion, precio);
          ArchivadorArticulo.agregarArticulo(articulo);
          
        llenarTabla();
        Limpiar();
    }//GEN-LAST:event_jBtnGuardarActionPerformed
// listo   HACER VALIDACION DE CAMPOS VACIOS
    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed

       if(jTblArticulos.getSelectedRow()==-1){
           JOptionPane.showMessageDialog(this, "Favor seleccionar un objeto a modificar en la tabla");
            return;
       }
        String codigo = jTxtCodigo.getText();
        int posicion = ArchivadorArticulo.posicionArticulo(codigo);
        String descripcion = jTxtDescripcion.getText();
        double precio = Double.parseDouble(jTxtPrecio.getText());
        
       //Almacena el nuevo artículo en el Archivador de artículos
         if(descripcion.equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar una descripcion correcta");
            return;
        }
          if(precio<0){
            JOptionPane.showMessageDialog(this, "Ingresar un precio valido");
            return;
        }
          Articulo articulo= new Articulo(codigo, descripcion, precio);
    
                               
        ArchivadorArticulo.modificarCiudad(posicion, articulo);
        
        this.llenarTabla();
          Limpiar();
        activarBotones();
        jTxtCodigo.setEnabled(true);
        Limpiar();
    }//GEN-LAST:event_jBtnModificarActionPerformed
// listo
    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
    if(jTblArticulos.getSelectedRow()==-1){
           JOptionPane.showMessageDialog(this, "Favor seleccionar un objeto a modificar en la tabla");
            return;
       }else{
        String codigo= jTxtCodigo.getText();
        ArchivadorArticulo.eliminarArticulo(codigo);
        this.llenarTabla();
         Limpiar();
         jTxtCodigo.setEnabled(true);
    }
    }//GEN-LAST:event_jBtnEliminarActionPerformed
// listo 
    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        activarBotones();
        Limpiar();
        jTxtCodigo.setEnabled(true);
        
    }//GEN-LAST:event_jBtnCancelarActionPerformed
 // listo 
    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed
// listo 
    private void jTblArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblArticulosMouseClicked

    if(evt.getClickCount()==2){
            int indice = jTblArticulos.getSelectedRow();
            desactivarBotones();
            jTxtCodigo.setEnabled(false);
            jTxtCodigo.setText((String) jTblArticulos.getValueAt(indice,0));
            jTxtDescripcion.setText((String) jTblArticulos.getValueAt(indice,1));
            jTxtPrecio.setText(String.valueOf(jTblArticulos.getValueAt(indice,2)));
        }
  
    }//GEN-LAST:event_jTblArticulosMouseClicked
// listo
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       llenarTabla();
       activarBotones();
    }//GEN-LAST:event_formWindowOpened
// listo 
    private void jTblArticulosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblArticulosFocusGained
        // TODO add your handling code here:
//    posicion= this.jTblArticulos.getSelectedRow();
//     this.desactivarBotones();
    }//GEN-LAST:event_jTblArticulosFocusGained
// SIN USO
    private void jTblArticulosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblArticulosFocusLost
        // TODO add your handling code here:
        //this.Limpiar();
    }//GEN-LAST:event_jTblArticulosFocusLost
// SIN USO
      private void llenarTabla() {
        //Actualiza la tabla a partir del ArrayList del archivador que contiene los artículos       tablaModelo.setRowCount(0);
       this.modeloTabla.setRowCount(0);
       
          for (Articulo articulo: ArchivadorArticulo.getArrayArticulo()) {
              Object [] objeto = new Object[3];
              objeto[0]= articulo.getCodigo();
                      objeto[1]=articulo.getDescripcion();
                            objeto[2]=articulo.getPrecio();
                            this.modeloTabla.addRow(objeto);
                      }
        
        
        
    }

    private void desactivarBotones() {
        jBtnGuardar.setEnabled(false);
        jBtnEliminar.setEnabled(true);
        jBtnModificar.setEnabled(true);
        jBtnCancelar.setEnabled(true);
    }
    private void activarBotones() {
        jBtnGuardar.setEnabled(true);
        jBtnEliminar.setEnabled(false);
        jBtnModificar.setEnabled(false);
        jBtnCancelar.setEnabled(false);
    }
    
    private void Limpiar(){
        jTxtCodigo.setText("");
        jTxtDescripcion.setText("");
        jTxtPrecio.setText("");
        activarBotones();
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTblArticulos;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDescripcion;
    private javax.swing.JTextField jTxtPrecio;
    // End of variables declaration//GEN-END:variables
}
