/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Vista;


import Capa_Acceso_Datos.Archivador_Usuarios;
import Capa_Logica_Negocios.*;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johnpaul
 */
public class FrmVentana_Admin extends javax.swing.JFrame {
    private static ContenidoAudioVisual contenidoAudVis=null;
    DefaultTableModel modeloTablaContenidos = new DefaultTableModel();
    DefaultTableModel modeloTablaReporteContenido = new DefaultTableModel();
    DefaultListModel modeloListaUsuarioReporte  = new DefaultListModel();
    
    private Usuario usuarioAux=null;
    private Usuario_Perfil perfilAux=null;
    
    public FrmVentana_Admin() {
        initComponents();
        this.setTitle("Elaborado por John Paul Alfaro Carballo");
        this.setSize(new Dimension(930,650));
        this.jToolBar1.setBackground(new Color(222,222,222,110));
        this.jTblDatosContenidoAudiovisual.setBackground(new Color(222,222,222,190));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.modeloTablaContenidos =   (DefaultTableModel)jTblDatosContenidoAudiovisual.getModel();       
         this.modeloTablaReporteContenido= (DefaultTableModel)jTblReportesContenido.getModel();
    }
    public FrmVentana_Admin(Usuario usuarioAuxp ,Usuario_Perfil perfilAuxp ) {
        initComponents();
        this.setTitle("Elaborado por John Paul Alfaro Carballo");
        this.setSize(new Dimension(930,650));
        this.jToolBar1.setBackground(new Color(222,222,222,110));
        this.jTblDatosContenidoAudiovisual.setBackground(new Color(222,222,222,190));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.modeloTablaContenidos =   (DefaultTableModel)jTblDatosContenidoAudiovisual.getModel();       
        this.modeloTablaReporteContenido= (DefaultTableModel)jTblReportesContenido.getModel();
        
        this.usuarioAux=usuarioAuxp;
        this.perfilAux=perfilAuxp;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jBtnGuardar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jBtnModificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnEliminar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblDatosContenidoAudiovisual = new javax.swing.JTable();
        jLblFondoPantalla = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblReportesContenido = new javax.swing.JTable();
        jLblFondoReporte1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtReporteUsuario = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLstReporteUsuarios = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jBtnLimpiarReporte = new javax.swing.JButton();
        jBtnSeleccionarUsuario = new javax.swing.JButton();
        jLblFondoReporte2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnAtras = new javax.swing.JMenu();
        jMnAtrasSub = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones disponibles"));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator5);

        jBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Objetos/salvar.png"))); // NOI18N
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setFocusable(false);
        jBtnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnGuardar);
        jToolBar1.add(jSeparator4);

        jBtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Objetos/escala.png"))); // NOI18N
        jBtnModificar.setText("Modificar");
        jBtnModificar.setFocusable(false);
        jBtnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnModificar);
        jToolBar1.add(jSeparator3);

        jBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Objetos/basura 2.png"))); // NOI18N
        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.setFocusable(false);
        jBtnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnEliminar);
        jToolBar1.add(jSeparator2);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Objetos/bloquear.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setFocusable(false);
        jBtnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnCancelar);
        jToolBar1.add(jSeparator1);

        jBtnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Objetos/consultante.png"))); // NOI18N
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.setFocusable(false);
        jBtnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultar);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(260, 80, 380, 130);

        jTblDatosContenidoAudiovisual.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTblDatosContenidoAudiovisual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTblDatosContenidoAudiovisual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Titulo", "Genero", "Es original?", "Fecha creacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblDatosContenidoAudiovisual.setOpaque(false);
        jTblDatosContenidoAudiovisual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblDatosContenidoAudiovisualMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblDatosContenidoAudiovisual);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 762, 319);

        jLblFondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Pantalla_Ventanas/FondoAminCatalogo.jpg"))); // NOI18N
        jPanel1.add(jLblFondoPantalla);
        jLblFondoPantalla.setBounds(-340, -20, 1270, 630);

        jTabbedPane1.addTab("Catalogo", jPanel1);

        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Informacion acerca de los contenidos descargados:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 50, 480, 30);

        jTblReportesContenido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTblReportesContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Tipo Contenido", "Genero", "Cant.Descarga", "Prom.Calificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTblReportesContenido);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 100, 880, 430);

        jLblFondoReporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Pantalla_Ventanas/FondoPantallaAdminReporte1.jpg"))); // NOI18N
        jPanel3.add(jLblFondoReporte1);
        jLblFondoReporte1.setBounds(0, 0, 930, 590);

        jTabbedPane2.addTab("Reporte de contenidos audiovisuales", jPanel3);

        jPanel4.setLayout(null);

        jTxtReporteUsuario.setEditable(false);
        jTxtReporteUsuario.setColumns(20);
        jTxtReporteUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtReporteUsuario.setRows(5);
        jTxtReporteUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Reporte de usuario seleccionado"));
        jScrollPane3.setViewportView(jTxtReporteUsuario);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(421, 12, 470, 520);

        jLstReporteUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Favor seleccionar un correo:"));
        jLstReporteUsuarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLstReporteUsuarios.setModel(modeloListaUsuarioReporte );
        jScrollPane4.setViewportView(jLstReporteUsuarios);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(12, 64, 280, 300);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Lista de cuentas de usuarios activos hoy:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(12, 30, 280, 28);

        jBtnLimpiarReporte.setText("LIMPIAR");
        jBtnLimpiarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarReporteActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnLimpiarReporte);
        jBtnLimpiarReporte.setBounds(152, 421, 100, 35);

        jBtnSeleccionarUsuario.setText("Seleccionar");
        jBtnSeleccionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeleccionarUsuarioActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnSeleccionarUsuario);
        jBtnSeleccionarUsuario.setBounds(152, 376, 100, 35);

        jLblFondoReporte2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Pantalla_Ventanas/FondoPantallaAdminReporte1.jpg"))); // NOI18N
        jPanel4.add(jLblFondoReporte2);
        jLblFondoReporte2.setBounds(0, -20, 940, 620);

        jTabbedPane2.addTab("Reporte de descargas por usuario", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reportes", jPanel2);

        jMnAtras.setText("< ATRAS >");

        jMnAtrasSub.setText("<<ATRAS>>");
        jMnAtrasSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnAtrasSubActionPerformed(evt);
            }
        });
        jMnAtras.add(jMnAtrasSub);

        jMenuBar1.add(jMnAtras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  //====================================================================================================
  // Ventana de administracion del catalogo   
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // Acciones a suceder dentro de este metodo:
        
        // Abre y envia que accion se va ejecutar en la otra ventana:
        JDlgVentana_AdminCatalogo dlgAdmin = new JDlgVentana_AdminCatalogo("", TIPO_ADMIN_OPCION.AGREGAR);
        dlgAdmin.setModal(true);
        dlgAdmin.setLocationRelativeTo(null);
        dlgAdmin.setVisible(true); 
        
        // regreso!!
        if(this.contenidoAudVis!=null){ 
          try {
              
            //  ContenidoAudioVisualBD.getInstance().agregarContenidoAudiovisual(contenidoAudVis);
              ContenidoAudioVisual.agregarContenidoAudiovisual(contenidoAudVis); // comando para guardar dentro del archivo
               
               
             } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Error al grabar el  contenido"+ "\n"+ex.toString()+ "\n"+ex.getMessage() ,
                        "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();// logra ver la linea de caida del codigo
                return;
            }
          
             //actualiza la tabla con el nuevo contenido
            llenaTabla_MantenimientoContenidos();   
            this.llenaTabla_ReporteContenido();
        }
        
        
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
    if(jTblDatosContenidoAudiovisual.getSelectedRow()>= 0){
        String codigo = jTblDatosContenidoAudiovisual.getValueAt(jTblDatosContenidoAudiovisual.getSelectedRow(),0).toString();  
        JDlgVentana_AdminCatalogo dlgDepartamento =
                new JDlgVentana_AdminCatalogo( codigo, TIPO_ADMIN_OPCION.MODIFICAR.MODIFICAR);
        dlgDepartamento.setModal(true);
        dlgDepartamento.setLocationRelativeTo(null);
        dlgDepartamento.setVisible(true);
        
        if(this.contenidoAudVis!= null){
            //Modifica el departamento de la lista
                try {
                    ContenidoAudioVisual.modificarContenidoAudiovisual(contenidoAudVis);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,"Error al modificar el  contenido audiovisual"+ "\n"+
                                               ex.toString()+ "\n"+ex.getMessage() , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                   this.llenaTabla_ReporteContenido();
                llenaTabla_MantenimientoContenidos(); //actualiza la tabla con el nuevo departamento
        }
        jTblDatosContenidoAudiovisual.clearSelection(); ; 

    }else{
            JOptionPane.showMessageDialog(null,"Debe seleccionar el departamento a modificar" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return;
        }
      jBtnGuardar.setEnabled(true);
      jBtnModificar.setEnabled(false);
      jBtnEliminar.setEnabled(false);                                      
        
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
     if(jTblDatosContenidoAudiovisual.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"Debe seleccionar el contenido a eliminar" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
            return;          
        }
      String codigo =jTblDatosContenidoAudiovisual.getValueAt(jTblDatosContenidoAudiovisual.getSelectedRow(),0).toString();
      try {
                ContenidoAudioVisual.eliminarContenidoAudiovisual(codigo); 
       } catch (Exception ex) {
                  JOptionPane.showMessageDialog(null,"Error al eliminar el  contendio audiovisual"+ "\n"+
                                                   ex.toString()+ "\n"+ex.getMessage() , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
                  System.exit(0);
       }
              llenaTabla_MantenimientoContenidos(); 
                 this.llenaTabla_ReporteContenido();
              jBtnGuardar.setEnabled(true);
              jBtnEliminar.setEnabled(false);
              jBtnModificar.setEnabled(false);
     
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // ACCIONES A HACER:
        desactivarBotonesModificarEliminar();
        limpiar();     
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        if(jTblDatosContenidoAudiovisual.getSelectedRow()>= 0){
          String codigo = jTblDatosContenidoAudiovisual.getValueAt(jTblDatosContenidoAudiovisual.getSelectedRow(),0).toString();  
          JDlgVentana_AdminCatalogo dlgDepartamento = new JDlgVentana_AdminCatalogo( codigo, TIPO_ADMIN_OPCION.CONSULTAR.CONSULTAR);//OJO se envía al contructor del JDialog el código del depto
          dlgDepartamento.setModal(true);
          dlgDepartamento.setLocationRelativeTo(null);
          dlgDepartamento.setVisible(true);
        }
        else{
              JOptionPane.showMessageDialog(null,"Debe seleccionar el contenido a consultar" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
              return;
        }
        jTblDatosContenidoAudiovisual.clearSelection();
        jBtnGuardar.setEnabled(true);
        jBtnModificar.setEnabled(false);
        jBtnEliminar.setEnabled(false);
    }//GEN-LAST:event_jBtnConsultarActionPerformed
//====================================================================================================
    

    
//*** EVENTOS SECUNDARIOS *** 
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           this.llenaTabla_MantenimientoContenidos();
           this.llenaTabla_ReporteContenido();
           this.desactivarBotonesModificarEliminar();
           this.llenaLista_ReporteUsuarios();
           this.jBtnLimpiarReporte.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jTblDatosContenidoAudiovisualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblDatosContenidoAudiovisualMouseClicked
          activarBotonesModificarEliminar();     
    }//GEN-LAST:event_jTblDatosContenidoAudiovisualMouseClicked

    private void jMnAtrasSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnAtrasSubActionPerformed
         FrmVentana_MenuOpcion frm = new FrmVentana_MenuOpcion(usuarioAux, perfilAux);
         frm.setLocationRelativeTo(null);
         frm.setVisible(true);        
         this.dispose(); 
    }//GEN-LAST:event_jMnAtrasSubActionPerformed
//***************************
    
//====================================================================================================
// Ventana de administracion de reporte usuarios
    private void jBtnSeleccionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeleccionarUsuarioActionPerformed
   int indice = jLstReporteUsuarios.getSelectedIndex();
      if(indice >= 0){
           //Usuario usuario= jLstReporteUsuarios.getSelectedValue();
           String correo= (String) jLstReporteUsuarios.getSelectedValue();
           
           this.jTxtReporteUsuario.setText(Validacion.retornaUsuario(correo).reporteDescargaAdmin());
           this.jBtnLimpiarReporte.setEnabled(true);
       }
      else{
           JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario de la lista" , "ERROR ENCONTRADO:",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jBtnSeleccionarUsuarioActionPerformed

    private void jBtnLimpiarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarReporteActionPerformed
     this.jTxtReporteUsuario.setText("");
     this.jBtnLimpiarReporte.setEnabled(false);
    }//GEN-LAST:event_jBtnLimpiarReporteActionPerformed
//====================================================================================================
    
    
    // <<<<<<<<<<<<<<<<<<<<<<<<<<<ACCIONES EXTRA>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    private void activarBotonesModificarEliminar() {
        jBtnGuardar.setEnabled(false);
        jBtnEliminar.setEnabled(true);
        jBtnModificar.setEnabled(true);
        jBtnCancelar.setEnabled(true);
    }
    private void desactivarBotonesModificarEliminar() {
        jBtnGuardar.setEnabled(true);
        jBtnEliminar.setEnabled(false);
        jBtnModificar.setEnabled(false);
        jBtnCancelar.setEnabled(false);
    }
    private void limpiar(){
        desactivarBotonesModificarEliminar();
    } 
    private void llenaTabla_MantenimientoContenidos() {
        modeloTablaContenidos.setRowCount(0);//Limpia la tabla
        Object[] datos = new Object[5];        
        ArrayList<ContenidoAudioVisual> lista= new ArrayList<ContenidoAudioVisual>();
        try {
            // trae contenido del archivo
           lista = ContenidoAudioVisual.listadoContendio(); 
        } catch (Exception e) { }
        for (int i = 0; i < lista.size(); i++) {
          datos[0] = lista.get(i).getCodigo();
          datos[1] = lista.get(i).getTitulo();
          datos[2] = lista.get(i).getGenero();
          datos[3] = lista.get(i).isEsOriginal()?"Es original":"No orignal";
          datos[4] = lista.get(i).devuelveAnnoCreacion();
          
          modeloTablaContenidos.addRow(datos);
        //Agrega el arreglo como una nueva fila de la tabla
        }
    }
    private void llenaTabla_ReporteContenido(){
         modeloTablaReporteContenido.setRowCount(0);//Limpia la tabla
        Object[] datos = new Object[5];        
        ArrayList<ContenidoAudioVisual> lista= new ArrayList<ContenidoAudioVisual>();
        try {
            // trae contenido del archivo
           lista = ContenidoAudioVisual.listadoContendio(); 
        } catch (Exception e) { }
        for (int i = 0; i < lista.size(); i++) {
          datos[0] = lista.get(i).getTitulo();
          datos[1] = (lista.get(i) instanceof ContenidoPelicula)?"Pelicula":"Serie";
          datos[2] = lista.get(i).getGenero();
          datos[3] = lista.get(i).getCantDescargas();
          datos[4] = lista.get(i).puntajeObtenido()+"%";
        
          modeloTablaReporteContenido.addRow(datos);
        }
      
    }
    private void llenaLista_ReporteUsuarios(){
      // Llena la lista con todos los usuarios registrados ademas, al dar click muestra las compras de los usuarios
      // Termianr esto 29-03-2020
      // terminado el 07-04-2020
      modeloListaUsuarioReporte.clear();
        for (Usuario usuario: Archivador_Usuarios.getArrayUsuarios()) {
            this.modeloListaUsuarioReporte.addElement(usuario.getCorreo());
        }
    }
    // <<<<<<<<<<<<<<<<<<<<<<<<<<<ACCIONES EXTRA>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    
    
    // Metodos set y get, sirven para traer el objeto desde la otra ventana a esta otra
    public static ContenidoAudioVisual getContenidoAudVis() {
        return contenidoAudVis;
    }
    public static void setContenidoAudVis(ContenidoAudioVisual contenido) {
       contenidoAudVis = contenido;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentana_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnLimpiarReporte;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnSeleccionarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblFondoPantalla;
    private javax.swing.JLabel jLblFondoReporte1;
    private javax.swing.JLabel jLblFondoReporte2;
    private javax.swing.JList<String> jLstReporteUsuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnAtras;
    private javax.swing.JMenuItem jMnAtrasSub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTblDatosContenidoAudiovisual;
    private javax.swing.JTable jTblReportesContenido;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea jTxtReporteUsuario;
    // End of variables declaration//GEN-END:variables
}
