/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Vista;

import Capa_Logica_Negocios.Usuario;
import Capa_Logica_Negocios.Usuario_Perfil;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmVentana_Registro_Informacion extends javax.swing.JFrame {
    
    Usuario usuarioAux=null;
    Usuario_Perfil perfilAux=null;
    DefaultTableModel modeloTablaContenidosPelicula = new DefaultTableModel();
    
    
    
    /**
     * Creates new form JDlgVentana_Registro2
     */
    public FrmVentana_Registro_Informacion() {
        initComponents();
        this.setTitle("Elaborado por John Paul Alfaro Carballo");
        this.setSize(new Dimension(900,580));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
            this.modeloTablaContenidosPelicula=(DefaultTableModel)this.jTblPerfiles.getModel();
  
    }
    public FrmVentana_Registro_Informacion(Usuario usuario) {
        this.usuarioAux=usuario;
       initComponents();
        this.setTitle("Elaborado por John Paul Alfaro Carballo");
        this.setSize(new Dimension(900,580));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
            this.modeloTablaContenidosPelicula=(DefaultTableModel)this.jTblPerfiles.getModel();  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtInformacionGeneral = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblPerfiles = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLblFondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de la cuenta"));
        jPanel1.setOpaque(false);

        jTxtInformacionGeneral.setEditable(false);
        jTxtInformacionGeneral.setColumns(20);
        jTxtInformacionGeneral.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTxtInformacionGeneral.setRows(5);
        jScrollPane1.setViewportView(jTxtInformacionGeneral);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 450, 540);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de perfiles"));
        jPanel2.setOpaque(false);

        jTblPerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de perfil", "Nombre de usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblPerfiles.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTblPerfilesFocusLost(evt);
            }
        });
        jTblPerfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblPerfilesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTblPerfiles);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(480, 120, 410, 250);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 410, 270, 41);

        jLabel1.setText("Si deseas ver la informacion del perfil, haz doble click sobre el....");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 80, 370, 30);

        jLblFondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Pantalla_Ventanas/FondoPantallaAdminReporte1.jpg"))); // NOI18N
        getContentPane().add(jLblFondoPantalla);
        jLblFondoPantalla.setBounds(0, 0, 960, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jTblPerfilesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblPerfilesFocusLost
        this.perfilAux=null;
        //        this.jTblPerfiles.clearSelection();
    }//GEN-LAST:event_jTblPerfilesFocusLost

    private void jTblPerfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblPerfilesMouseClicked
        perfilAux=this.usuarioAux.getArrayPerfiles().get(this.jTblPerfiles.getSelectedRow());

        int opcion=JOptionPane.showConfirmDialog(this,perfilAux.toString(),
            "Perfil seleccionado:", JOptionPane.YES_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(opcion==0){ // Opcion de confirmacion
            this.perfilAux=null;
            this.jTblPerfiles.clearSelection();
        }

    }//GEN-LAST:event_jTblPerfilesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ACCIONES QUE SE VAN HACER CUADNO ESTA VENTANA SE CIEERE
        this.dispose();
        FrmVentana_InicioSesion frm = new FrmVentana_InicioSesion();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //Cuando se abre este panel, se hara esto!!!
        this.jTxtInformacionGeneral.setText(usuarioAux.toString());
        this.llenaTabla();
    }//GEN-LAST:event_formWindowOpened

    
    
       private void llenaTabla(){
         modeloTablaContenidosPelicula.setRowCount(0);//Limpia la tabla
        Object[] datos = new Object[2];        
        ArrayList<Usuario_Perfil> lista= new ArrayList();
        lista=usuarioAux.getArrayPerfiles();
        for (int i = 0; i < lista.size(); i++) {
                    datos[0] = i+1;
                    datos[1] = lista.get(i).getNombre();
                    modeloTablaContenidosPelicula.addRow(datos);
                    //Agrega el arreglo como una nueva fila de la tabla
            }
    }
    
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentana_Registro_Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentana_Registro_Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentana_Registro_Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentana_Registro_Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentana_Registro_Informacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblFondoPantalla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblPerfiles;
    private javax.swing.JTextArea jTxtInformacionGeneral;
    // End of variables declaration//GEN-END:variables
}
